(() => {
  const baseLevels = [
    {
      id: "dasar",
      label: "Dasar",
      icon: "🌱",
      description: "Kosakata inti dan kalimat pendek untuk kehidupan sekolah.",
      lessons: [
        ["Salam dan sapaan", "السَّلَامُ عَلَيْكُمْ", "as-salāmu ‘alaikum", "Semoga keselamatan tercurah kepadamu.", "Jawaban salam yang tepat ialah …", ["وَعَلَيْكُمُ السَّلَامُ", "مَعَ السَّلَامَةِ", "شُكْرًا"], 0],
        ["Perkenalan diri", "اِسْمِي أَحْمَدُ", "ismī Aḥmadu", "Nama saya Ahmad.", "Kata اِسْمِي berarti …", ["kelasku", "namaku", "bukuku"], 1],
        ["Benda di kelas", "هٰذَا كِتَابٌ", "hādzā kitābun", "Ini sebuah buku.", "Kata كِتَابٌ berarti …", ["buku", "pena", "meja"], 0],
        ["Angka 1–10", "وَاحِدٌ، اِثْنَانِ، ثَلَاثَةٌ", "wāḥidun, itsnāni, tsalātsatun", "Satu, dua, tiga.", "Angka ثَلَاثَةٌ ialah …", ["dua", "tiga", "empat"], 1],
        ["Keluarga", "هٰذِهِ أُمِّي", "hādzihī ummī", "Ini ibu saya.", "Kata أُمِّي berarti …", ["ayahku", "ibuku", "saudaraku"], 1],
        ["Hari dan waktu", "اَلْيَوْمُ يَوْمُ الْجُمُعَةِ", "al-yaumu yaumul-jumu‘ati", "Hari ini hari Jumat.", "Kata اَلْيَوْمُ berarti …", ["hari ini", "kemarin", "besok"], 0],
      ],
    },
    {
      id: "menengah",
      label: "Menengah",
      icon: "🧭",
      description: "Pola kalimat, pertanyaan, dan aktivitas sehari-hari.",
      lessons: [
        ["Kalimat nominal", "اَلْمَدْرَسَةُ نَظِيفَةٌ", "al-madrasatu naẓīfatun", "Sekolah itu bersih.", "Sifat yang digunakan pada kalimat ialah …", ["bersih", "besar", "jauh"], 0],
        ["Kalimat kerja", "يَقْرَأُ الطَّالِبُ الْكِتَابَ", "yaqra’ut-thālibul-kitāba", "Murid membaca buku.", "Kata kerja يَقْرَأُ berarti …", ["menulis", "membaca", "mendengar"], 1],
        ["Kata tanya", "أَيْنَ الْمَسْجِدُ؟", "ainal-masjidu?", "Di mana masjid?", "Kata tanya أَيْنَ digunakan untuk menanyakan …", ["tempat", "waktu", "jumlah"], 0],
        ["Kegiatan harian", "أَذْهَبُ إِلَى الْمَدْرَسَةِ صَبَاحًا", "adz-habu ilal-madrasati shabāḥan", "Saya pergi ke sekolah pada pagi hari.", "Kegiatan pada kalimat berlangsung …", ["pagi", "siang", "malam"], 0],
        ["Arah dan tempat", "اَلْمَكْتَبَةُ بِجَانِبِ الْفَصْلِ", "al-maktabatu bijānil-fil", "Perpustakaan berada di samping kelas.", "بِجَانِبِ berarti …", ["di depan", "di samping", "di belakang"], 1],
        ["Adab belajar", "أَسْتَأْذِنُ قَبْلَ الْكَلَامِ", "asta’dzinu qablal-kalāmi", "Saya meminta izin sebelum berbicara.", "Sikap pada kalimat menunjukkan …", ["ketergesa-gesaan", "adab", "kelalaian"], 1],
      ],
    },
    {
      id: "mahir",
      label: "Mahir",
      icon: "🏆",
      description: "Membaca, menyimpulkan, dan menyampaikan gagasan sederhana.",
      lessons: [
        ["Membaca paragraf", "أُحِبُّ الْعِلْمَ لِأَنَّهُ نُورٌ", "uḥibbul-‘ilma li-annahu nūrun", "Saya mencintai ilmu karena ilmu adalah cahaya.", "Alasan mencintai ilmu pada kalimat ialah …", ["ilmu adalah cahaya", "ilmu itu sulit", "ilmu itu mahal"], 0],
        ["Menyatakan pendapat", "فِي رَأْيِي، الصِّدْقُ أَسَاسُ الثِّقَةِ", "fī ra’yī, ash-shidqu asāsuts-tsiqati", "Menurut saya, kejujuran adalah dasar kepercayaan.", "Ungkapan فِي رَأْيِي digunakan untuk …", ["meminta izin", "menyatakan pendapat", "mengucapkan salam"], 1],
        ["Sebab dan akibat", "نَجَحَ لِأَنَّهُ اجْتَهَدَ", "najaḥa li-annahu ijtahada", "Ia berhasil karena bersungguh-sungguh.", "Penyebab keberhasilan ialah …", ["bersungguh-sungguh", "terlambat", "beristirahat"], 0],
        ["Membandingkan", "الْعِلْمُ أَنْفَعُ مِنَ الْمَالِ", "al-‘ilmu anfa‘u minal-māli", "Ilmu lebih bermanfaat daripada harta.", "Pola أَنْفَعُ مِنْ menunjukkan …", ["perbandingan", "larangan", "pertanyaan"], 0],
        ["Ringkasan teks", "يَحْفَظُ الْمُسْلِمُ الْبِيئَةَ وَلَا يُفْسِدُهَا", "yaḥfaẓul-muslimul-bī’ata wa lā yufsiduhā", "Seorang Muslim menjaga lingkungan dan tidak merusaknya.", "Inti kalimat ialah …", ["menjaga lingkungan", "meninggalkan sekolah", "membeli barang"], 0],
        ["Presentasi singkat", "سَأَتَحَدَّثُ عَنْ أَهَمِّيَّةِ الْأَمَانَةِ", "sa-ataḥaddatsu ‘an ahammiyyatil-amānati", "Saya akan berbicara tentang pentingnya amanah.", "Topik presentasi ialah …", ["keberanian", "amanah", "perjalanan"], 1],
      ],
    },
    {
      id: "percakapan",
      label: "Percakapan",
      icon: "💬",
      description: "Dialog praktis di sekolah, masjid, rumah, dan ruang publik.",
      lessons: [
        ["Di kelas", "هَلْ فَهِمْتَ الدَّرْسَ؟ نَعَمْ، فَهِمْتُ", "hal fahimtad-darsa? na‘am, fahimtu", "Apakah kamu memahami pelajaran? Ya, saya paham.", "Jawaban yang menunjukkan paham ialah …", ["لَا أَعْرِفُ", "نَعَمْ، فَهِمْتُ", "إِلَى اللِّقَاءِ"], 1],
        ["Di perpustakaan", "أُرِيدُ أَنْ أَسْتَعِيرَ هٰذَا الْكِتَابَ", "urīdu an asta‘īra hādzal-kitāba", "Saya ingin meminjam buku ini.", "Tujuan penutur ialah …", ["meminjam buku", "membeli makanan", "mencari masjid"], 0],
        ["Di masjid", "مَتَى تُقَامُ الصَّلَاةُ؟", "matā tuqāmush-shalātu?", "Kapan sholat didirikan?", "Kata tanya مَتَى menanyakan …", ["orang", "waktu", "tempat"], 1],
        ["Meminta arah", "كَيْفَ أَذْهَبُ إِلَى الْمُصَلَّى؟", "kaifa adz-habu ilal-mushallā?", "Bagaimana saya pergi ke mushala?", "Percakapan ini dipakai ketika …", ["meminta arah", "memesan makanan", "berpamitan"], 0],
        ["Menawarkan bantuan", "هَلْ تَحْتَاجُ إِلَى مُسَاعَدَةٍ؟", "hal taḥtāju ilā musā‘adatin?", "Apakah kamu memerlukan bantuan?", "Nilai yang dilatih ialah …", ["kepedulian", "kesombongan", "ketidakjujuran"], 0],
        ["Berdiskusi santun", "أَحْتَرِمُ رَأْيَكَ، وَلَكِنْ لِي رَأْيٌ آخَرُ", "aḥtarimu ra’yaka, walākin lī ra’yun ākharu", "Saya menghormati pendapatmu, tetapi saya memiliki pendapat lain.", "Ungkapan ini menunjukkan …", ["ejekan", "perbedaan yang santun", "penolakan kasar"], 1],
      ],
    },
  ];

  const expansions = {
    dasar: [
      ["Warna", "اَلْكِتَابُ أَزْرَقُ", "al-kitābu azraqu", "Buku itu berwarna biru.", "Kata أَزْرَقُ berarti …", ["merah", "biru", "hijau"], 1],
      ["Anggota tubuh", "هٰذِهِ يَدِي", "hādzihī yadī", "Ini tangan saya.", "Kata يَدِي berarti …", ["tanganku", "mataku", "kepalaku"], 0],
      ["Pakaian", "أَلْبَسُ الْقَمِيصَ", "albasul-qamīsha", "Saya mengenakan kemeja.", "Kata الْقَمِيصَ berarti …", ["sepatu", "kemeja", "peci"], 1],
      ["Makanan", "آكُلُ الْأَرُزَّ", "ākulul-aruzza", "Saya makan nasi.", "Kata kerja آكُلُ berarti …", ["saya makan", "saya minum", "saya membaca"], 0],
      ["Minuman", "أَشْرَبُ الْمَاءَ", "asyrabul-mā'a", "Saya minum air.", "Kata الْمَاءَ berarti …", ["susu", "air", "teh"], 1],
      ["Cuaca", "اَلْجَوُّ مُشْمِسٌ", "al-jawwu musymsun", "Cuaca cerah.", "Kata مُشْمِسٌ berarti …", ["cerah", "hujan", "dingin"], 0],
      ["Rumah", "هٰذَا بَيْتِي", "hādzā baitī", "Ini rumah saya.", "Kata بَيْتِي berarti …", ["sekolahku", "rumahku", "kamarku"], 1],
      ["Kamar", "غُرْفَتِي نَظِيفَةٌ", "ghurfatī naẓīfatun", "Kamar saya bersih.", "Kata غُرْفَتِي berarti …", ["kamarku", "kelasku", "tamanku"], 0],
      ["Hobi", "هَوَايَتِي الْقِرَاءَةُ", "hiwāyatī al-qirā'atu", "Hobi saya membaca.", "Hobi pada kalimat ialah …", ["menulis", "membaca", "berenang"], 1],
      ["Olahraga", "أَلْعَبُ كُرَةَ الْقَدَمِ", "al'abu kuratal-qadami", "Saya bermain sepak bola.", "Kata أَلْعَبُ berarti …", ["saya bermain", "saya belajar", "saya berjalan"], 0],
      ["Kendaraan", "أَذْهَبُ بِالدَّرَّاجَةِ", "adz-habu bid-darrājati", "Saya pergi dengan sepeda.", "Kendaraan pada kalimat ialah …", ["bus", "sepeda", "kereta"], 1],
      ["Profesi", "أَبِي مُعَلِّمٌ", "abī mu'allimun", "Ayah saya seorang guru.", "Kata مُعَلِّمٌ berarti …", ["dokter", "guru", "petani"], 1],
      ["Kata sifat", "اَلْفَصْلُ وَاسِعٌ", "al-fashlu wāsi'un", "Kelas itu luas.", "Kata وَاسِعٌ berarti …", ["sempit", "luas", "tinggi"], 1],
      ["Ucapan terima kasih", "شُكْرًا جَزِيلًا", "syukran jazīlan", "Terima kasih banyak.", "Ungkapan ini digunakan untuk …", ["meminta maaf", "berterima kasih", "berpamitan"], 1],
    ],
    menengah: [
      ["Kata ganti", "هُوَ طَالِبٌ مُجْتَهِدٌ", "huwa thālibun mujtahidun", "Dia murid laki-laki yang rajin.", "Kata هُوَ berarti …", ["dia laki-laki", "dia perempuan", "mereka"], 0],
      ["Kepemilikan", "هٰذَا كِتَابُ الْمُعَلِّمِ", "hādzā kitābul-mu'allimi", "Ini buku guru.", "Susunan tersebut menunjukkan …", ["larangan", "kepemilikan", "pertanyaan"], 1],
      ["Kata tunjuk", "هٰذِهِ سَبُّورَةٌ", "hādzihī sabbūratun", "Ini papan tulis.", "هٰذِهِ digunakan untuk kata benda …", ["mudzakkar", "muannats", "jamak saja"], 1],
      ["Keterangan waktu", "أَدْرُسُ بَعْدَ الْمَغْرِبِ", "adrusu ba'dal-maghribi", "Saya belajar setelah Maghrib.", "Kapan kegiatan belajar berlangsung?", ["sebelum Subuh", "setelah Maghrib", "siang hari"], 1],
      ["Keterangan tempat", "الْكِتَابُ فَوْقَ الْمَكْتَبِ", "al-kitābu fauqal-maktabi", "Buku berada di atas meja.", "Kata فَوْقَ berarti …", ["di bawah", "di atas", "di antara"], 1],
      ["Kalimat negatif", "لَا أَكْذِبُ", "lā akdzibu", "Saya tidak berdusta.", "Partikel لَا pada kalimat menyatakan …", ["perintah", "peniadaan", "pertanyaan"], 1],
      ["Perintah", "اِقْرَأِ الدَّرْسَ", "iqra'id-darsa", "Bacalah pelajaran.", "Kalimat tersebut berbentuk …", ["perintah", "berita", "larangan"], 0],
      ["Larangan", "لَا تُهْمِلْ وَاجِبَكَ", "lā tuhml wājibaka", "Jangan abaikan tugasmu.", "Kalimat ini berisi …", ["pujian", "larangan", "permintaan arah"], 1],
      ["Kebiasaan baik", "أُرَتِّبُ غُرْفَتِي كُلَّ يَوْمٍ", "urattibu ghurfatī kulla yaumin", "Saya merapikan kamar setiap hari.", "Seberapa sering kegiatan dilakukan?", ["setiap hari", "setiap bulan", "sekali"], 0],
      ["Kesehatan", "أَغْسِلُ يَدَيَّ قَبْلَ الطَّعَامِ", "aghsilu yadayya qablath-tha'āmi", "Saya mencuci tangan sebelum makan.", "Kegiatan dilakukan … makan.", ["setelah", "sebelum", "ketika"], 1],
      ["Lingkungan", "نَضَعُ النُّفَايَاتِ فِي مَكَانِهَا", "nadha'un-nufāyāti fī makānihā", "Kami menaruh sampah pada tempatnya.", "Nilai utama kalimat ialah …", ["kebersihan", "persaingan", "perjalanan"], 0],
      ["Perpustakaan", "أَبْحَثُ عَنِ الْمَرْجِعِ", "abḥatsu 'anil-marji'i", "Saya mencari buku rujukan.", "Kata أَبْحَثُ berarti …", ["saya mencari", "saya meminjam", "saya mengembalikan"], 0],
      ["Menyatakan kemampuan", "أَسْتَطِيعُ أَنْ أَقْرَأَ", "astathī'u an aqra'a", "Saya mampu membaca.", "أَسْتَطِيعُ berarti …", ["saya ingin", "saya mampu", "saya harus"], 1],
      ["Menyatakan keinginan", "أُرِيدُ أَنْ أَتَعَلَّمَ", "urīdu an ata'allama", "Saya ingin belajar.", "Kata أُرِيدُ berarti …", ["saya ingin", "saya tahu", "saya selesai"], 0],
    ],
    mahir: [
      ["Gagasan utama", "اَلْعِلْمُ يَبْنِي الْمُسْتَقْبَلَ", "al-'ilmu yabnil-mustaqbala", "Ilmu membangun masa depan.", "Gagasan utama kalimat ialah …", ["masa depan dibangun dengan ilmu", "ilmu harus disimpan", "masa depan tidak penting"], 0],
      ["Kalimat majemuk", "دَرَسْتُ ثُمَّ كَتَبْتُ الْخُلَاصَةَ", "darastu tsumma katabtul-khulāshata", "Saya belajar kemudian menulis ringkasan.", "Kata ثُمَّ menunjukkan …", ["urutan", "sebab", "larangan"], 0],
      ["Syarat sederhana", "إِنْ تَجْتَهِدْ تَنْجَحْ", "in tajtahid tanjaḥ", "Jika bersungguh-sungguh, kamu akan berhasil.", "Hubungan kalimat ialah …", ["syarat dan hasil", "perbandingan", "pertanyaan"], 0],
      ["Tujuan", "أَذْهَبُ إِلَى الْمَكْتَبَةِ لِأَقْرَأَ", "adz-habu ilal-maktabati li-aqra'a", "Saya pergi ke perpustakaan untuk membaca.", "Tujuan pergi ke perpustakaan ialah …", ["menulis", "membaca", "bermain"], 1],
      ["Alasan", "أَحْفَظُ الْوَقْتَ لِأَنَّهُ أَمَانَةٌ", "aḥfaẓul-waqta li-annahu amānatun", "Saya menjaga waktu karena waktu adalah amanah.", "Alasan menjaga waktu ialah …", ["waktu adalah amanah", "waktu sangat panjang", "waktu dapat diulang"], 0],
      ["Kesimpulan", "إِذَنْ، الصِّدْقُ طَرِيقُ النَّجَاحِ", "idzan, ash-shidqu tharīqun-najāḥi", "Jadi, kejujuran adalah jalan keberhasilan.", "Kata إِذَنْ menandai …", ["sapaan", "kesimpulan", "larangan"], 1],
      ["Menyetujui", "أُوَافِقُكَ فِي هٰذَا الرَّأْيِ", "uwāfiquka fī hādzar-ra'yi", "Saya setuju dengan pendapat ini.", "Penutur menyatakan …", ["persetujuan", "kebingungan", "permohonan"], 0],
      ["Tidak setuju santun", "لَا أُوَافِقُ، وَلِي سَبَبٌ", "lā uwāfiqu, wa lī sababun", "Saya tidak setuju dan memiliki alasan.", "Sikap ilmiah yang ditunjukkan ialah …", ["menolak tanpa alasan", "berbeda dengan alasan", "mengejek"], 1],
      ["Menyajikan bukti", "الدَّلِيلُ عَلَى ذٰلِكَ هُوَ النَّصُّ", "ad-dalīlu 'alā dzālika huwan-nashshu", "Buktinya adalah teks tersebut.", "Kalimat digunakan untuk …", ["menunjukkan bukti", "berpamitan", "meminta izin"], 0],
      ["Merangkum", "خُلَاصَةُ النَّصِّ أَنَّ الْأَمَانَةَ وَاجِبَةٌ", "khulāshatun-nashshi annal-amānata wājibatun", "Ringkasan teks: amanah itu wajib.", "Isi ringkasan ialah …", ["amanah itu wajib", "teks itu panjang", "ringkasan tidak perlu"], 0],
      ["Sebab sosial", "نَتَعَاوَنُ لِنَخْدِمَ الْمُجْتَمَعَ", "nata'āwanu linakhdimal-mujtama'a", "Kami bekerja sama untuk melayani masyarakat.", "Tujuan kerja sama ialah …", ["melayani masyarakat", "mencari pujian", "menghindari tugas"], 0],
      ["Menjaga bumi", "يَجِبُ أَنْ نَحْفَظَ الْأَرْضَ", "yajibu an naḥfaẓal-ardha", "Kita wajib menjaga bumi.", "Kata يَجِبُ menunjukkan …", ["kewajiban", "kemungkinan", "masa lalu"], 0],
      ["Teks sejarah", "اِزْدَهَرَ الْعِلْمُ فِي الْحَضَارَةِ الْإِسْلَامِيَّةِ", "izdaharal-'ilmu fil-ḥadhāratil-islāmiyyati", "Ilmu berkembang dalam peradaban Islam.", "Apa yang berkembang?", ["perdagangan", "ilmu", "perjalanan"], 1],
      ["Ajakan akademik", "لِنَقْرَأِ الْمَصْدَرَ قَبْلَ الْحُكْمِ", "linaqra'il-mashdara qablal-ḥukmi", "Mari membaca sumber sebelum menilai.", "Pesan utama kalimat ialah …", ["periksa sumber", "cepat menilai", "abaikan bukti"], 0],
    ],
    percakapan: [
      ["Berkenalan", "مَا اسْمُكَ؟ اِسْمِي عَلِيٌّ", "mā ismuka? ismī 'Aliyyun", "Siapa namamu? Nama saya Ali.", "Pertanyaan menanyakan …", ["alamat", "nama", "kelas"], 1],
      ["Menanyakan kabar", "كَيْفَ حَالُكَ؟ أَنَا بِخَيْرٍ", "kaifa ḥāluka? anā bikhairin", "Apa kabar? Saya baik.", "Jawaban yang diberikan ialah …", ["saya baik", "saya pergi", "saya belajar"], 0],
      ["Meminta izin masuk", "هَلْ أَسْتَطِيعُ الدُّخُولَ؟", "hal astathī'ud-dukhūla?", "Bolehkah saya masuk?", "Percakapan ini digunakan untuk …", ["meminta izin", "meminta buku", "menawarkan makanan"], 0],
      ["Meminta pengulangan", "مِنْ فَضْلِكَ، أَعِدِ الْكَلَامَ", "min fadhlika, a'idil-kalāma", "Tolong ulangi ucapan itu.", "Penutur meminta …", ["penjelasan tertulis", "pengulangan", "perjalanan"], 1],
      ["Meminta penjelasan", "لَا أَفْهَمُ، هَلْ تَشْرَحُ؟", "lā afhamu, hal tasyraḥu?", "Saya belum paham, apakah Anda dapat menjelaskan?", "Kebutuhan penutur ialah …", ["penjelasan", "makanan", "arah"], 0],
      ["Meminjam alat tulis", "هَلْ أَسْتَعِيرُ قَلَمَكَ؟", "hal asta'īru qalamaka?", "Bolehkah saya meminjam penamu?", "Benda yang hendak dipinjam ialah …", ["buku", "pena", "penggaris"], 1],
      ["Membeli makanan", "بِكَمْ هٰذَا الطَّعَامُ؟", "bikam hādzath-tha'āmu?", "Berapa harga makanan ini?", "Kata بِكَمْ digunakan untuk menanyakan …", ["harga", "tempat", "waktu"], 0],
      ["Di halte", "مَتَى تَصِلُ الْحَافِلَةُ؟", "matā tashilul-ḥāfilatu?", "Kapan bus tiba?", "Yang ditanyakan ialah …", ["arah bus", "waktu tiba", "harga tiket"], 1],
      ["Menjenguk teman", "شَفَاكَ اللَّهُ", "syafākallāhu", "Semoga Allah Subhanahu Wata'ala menyembuhkanmu.", "Ungkapan ini disampaikan kepada …", ["orang sakit", "orang bepergian", "orang belajar"], 0],
      ["Bertamu", "أَهْلًا وَسَهْلًا، تَفَضَّلْ", "ahlan wa sahlan, tafadhdhal", "Selamat datang, silakan masuk.", "Ungkapan menunjukkan …", ["sambutan", "penolakan", "perpisahan"], 0],
      ["Menyusun janji", "نَلْتَقِي بَعْدَ الظُّهْرِ", "naltaqī ba'dazh-zhuhri", "Kita bertemu setelah Dzuhur.", "Waktu pertemuan ialah …", ["sebelum Subuh", "setelah Dzuhur", "setelah Isya"], 1],
      ["Meminta maaf", "أَعْتَذِرُ عَنْ خَطَئِي", "a'tadziru 'an khatha'ī", "Saya meminta maaf atas kesalahan saya.", "Penutur sedang …", ["berterima kasih", "meminta maaf", "mengundang"], 1],
      ["Memberi saran", "مِنَ الْأَفْضَلِ أَنْ تُرَاجِعَ دَرْسَكَ", "minal-afdhali an turāji'a darsaka", "Sebaiknya kamu mengulang pelajaranmu.", "Kalimat berisi …", ["saran", "larangan keras", "sapaan"], 0],
      ["Berpamitan", "إِلَى اللِّقَاءِ، فِي أَمَانِ اللَّهِ", "ilal-liqā', fī amānillāhi", "Sampai jumpa, semoga dalam penjagaan Allah Subhanahu Wata'ala.", "Ungkapan digunakan ketika …", ["bertemu", "berpamitan", "meminta bantuan"], 1],
    ],
  };

  const levels = baseLevels.map((level) => ({
    ...level,
    lessons: [...level.lessons, ...(expansions[level.id] || [])].map(([title, arabic, transliteration, meaning, question, options, answer], index) => ({
      id: `${level.id}-${index + 1}`,
      title,
      arabic,
      transliteration,
      meaning,
      question,
      options,
      answer,
    })),
  }));

  window.PAIBP_ARABIC = { levels };
})();
