(() => {
  const chapters = [
    {
      id: "VII-1", grade: "VII", semester: "Gasal", number: 1, allocation: 9,
      element: "Al Qur'an dan Hadits",
      title: "Al Qur'an dan Sunnah sebagai Pedoman Hidup",
      overview: "Al Qur'an merupakan wahyu Allah Subhanahu Wata'ala dan sunnah Nabi Muhammad Sholallohu 'Alaihi Wasallam menjadi penjelas serta teladan penerapannya. Keduanya membimbing manusia dalam akidah, ibadah, akhlak, dan kehidupan sosial.",
      objectives: ["Menjelaskan kedudukan Al Qur'an dan sunnah", "Membedakan fungsi Al Qur'an dan sunnah", "Menerapkan keduanya ketika mengambil keputusan"],
      concepts: [
        ["Al Qur'an sebagai wahyu", "Al Qur'an diturunkan kepada Nabi Muhammad Sholallohu 'Alaihi Wasallam sebagai petunjuk bagi manusia. Isinya memuat prinsip keimanan, ibadah, akhlak, hukum, kisah, dan arahan membangun kehidupan yang baik."],
        ["Sunnah sebagai penjelas", "Sunnah mencakup perkataan, perbuatan, dan ketetapan Nabi Muhammad Sholallohu 'Alaihi Wasallam. Sunnah menjelaskan ajaran Al Qur'an, memberikan contoh pelaksanaan, dan menetapkan tuntunan yang tidak dijelaskan secara terperinci."],
        ["Hubungan Al Qur'an dan sunnah", "Keduanya tidak dipertentangkan. Pemahaman ajaran Islam dilakukan dengan mendahulukan Al Qur'an, kemudian memahami penjelasannya melalui sunnah yang dapat dipertanggungjawabkan."],
        ["Adab menjadikan pedoman", "Murid membaca dengan hormat, mempelajari makna, bertanya kepada guru yang kompeten, menghindari pemotongan dalil, serta berusaha mengamalkan nilai yang telah dipahami."],
      ],
      applications: ["Memeriksa dalil dan penjelasan guru sebelum menyimpulkan persoalan agama", "Membiasakan membaca Al Qur'an beserta terjemah dan penjelasannya", "Meneladani kejujuran, kasih sayang, dan tanggung jawab Nabi"],
      questions: ["Mengapa Al Qur'an memerlukan penjelasan sunnah?", "Bagaimana cara memeriksa informasi agama di media sosial?", "Tuliskan satu keputusan harian yang dapat dibimbing nilai Al Qur'an dan sunnah."],
      project: "Susun peta keputusan bertema 'Dalil–Makna–Tindakan' berdasarkan satu persoalan nyata di sekolah.",
    },
    {
      id: "VII-2", grade: "VII", semester: "Gasal", number: 2, allocation: 9,
      element: "Akidah",
      title: "Meneladan Nama dan Sifat Allah Subhanahu Wata'ala untuk Kebaikan Hidup",
      overview: "Mengenal nama dan sifat Allah Subhanahu Wata'ala menguatkan iman serta membentuk kesadaran bahwa setiap perbuatan berada dalam pengetahuan-Nya. Manusia tidak menyamai sifat Allah, tetapi dapat meneladan nilai kebaikan yang sesuai dengan kedudukannya sebagai hamba.",
      objectives: ["Menjelaskan makna beberapa asmaulhusna", "Menghubungkan iman dengan pembentukan akhlak", "Menunjukkan perilaku teliti, penyayang, dan bertanggung jawab"],
      concepts: [
        ["Al-'Alim dan kesungguhan belajar", "Allah Subhanahu Wata'ala Maha Mengetahui segala sesuatu. Kesadaran ini mendorong murid mencintai ilmu, jujur ketika belajar, dan tidak merasa paling mengetahui."],
        ["Al-Khabir dan ketelitian", "Allah Subhanahu Wata'ala Maha Teliti terhadap yang tampak maupun tersembunyi. Nilai yang dapat diterapkan ialah memeriksa informasi, bekerja cermat, dan mempertanggungjawabkan keputusan."],
        ["As-Sami' dan Al-Bashir", "Allah Subhanahu Wata'ala Maha Mendengar dan Maha Melihat. Iman kepada-Nya membangun pengendalian diri, kesantunan berbicara, serta kehati-hatian dalam ruang nyata dan digital."],
        ["Ar-Rahman dan kasih sayang", "Kasih sayang Allah Subhanahu Wata'ala meliputi seluruh makhluk. Murid mewujudkan nilai kasih sayang melalui pertolongan, kepedulian, perlindungan terhadap yang lemah, dan menjaga lingkungan."],
      ],
      applications: ["Tidak menyontek walaupun tidak diawasi", "Memeriksa ulang tugas sebelum dikumpulkan", "Mendengarkan teman dengan empati dan tidak merendahkan"],
      questions: ["Apa hubungan Al-Khabir dengan literasi digital?", "Mengapa meneladan nilai asmaulhusna tidak berarti menyamai Allah?", "Berikan contoh pengendalian diri karena merasa diawasi Allah Subhanahu Wata'ala."],
      project: "Buat jurnal tujuh hari penerapan satu nilai asmaulhusna dalam tindakan konkret.",
    },
    {
      id: "VII-3", grade: "VII", semester: "Gasal", number: 3, allocation: 9,
      element: "Fikih",
      title: "Menghadirkan Sholat dan Dzikir dalam Kehidupan",
      overview: "Sholat membangun hubungan seorang hamba dengan Allah Subhanahu Wata'ala, sedangkan dzikir menjaga kesadaran hati kepada-Nya. Ibadah yang benar tidak berhenti pada gerakan dan ucapan, tetapi membentuk disiplin, ketenangan, serta akhlak.",
      objectives: ["Menjelaskan hakikat dan kedudukan sholat", "Mempraktikkan dzikir dengan adab yang benar", "Menganalisis pengaruh ibadah terhadap perilaku"],
      concepts: [
        ["Makna sholat", "Sholat adalah ibadah yang terdiri atas ucapan dan gerakan tertentu, dimulai dengan takbiratul ihram dan diakhiri salam. Ketepatan syarat, rukun, dan waktu menjadi bagian dari kesungguhan beribadah."],
        ["Khusyuk dan kesadaran", "Khusyuk dilatih melalui niat yang lurus, memahami bacaan, mengurangi gangguan, dan menghadirkan rasa menghadap Allah Subhanahu Wata'ala. Khusyuk tumbuh melalui latihan, bukan sekedar menunggu perasaan."],
        ["Dzikir dan ketenangan", "Dzikir dilakukan dengan lisan dan hati melalui bacaan yang baik serta kesadaran terhadap kebesaran Allah Subhanahu Wata'ala. Dzikir membantu menata emosi dan mengingatkan manusia agar tidak sombong."],
        ["Dampak sosial ibadah", "Sholat yang dihayati mencegah perbuatan buruk, menguatkan disiplin, kebersihan, persaudaraan, dan tanggung jawab. Ukuran keberhasilan ibadah juga terlihat dari perbaikan perilaku."],
      ],
      applications: ["Membuat pengingat sholat yang tidak mengganggu kegiatan belajar", "Menjaga kebersihan tempat ibadah", "Menggunakan dzikir untuk menenangkan diri sebelum merespons konflik"],
      questions: ["Mengapa sholat harus memengaruhi perilaku?", "Apa perbedaan dzikir yang hanya diucapkan dan dzikir yang dihayati?", "Susun strategi melatih khusyuk selama satu pekan."],
      project: "Buat pemantauan ibadah dan refleksi akhlak selama tujuh hari tanpa mencantumkan data yang bersifat pribadi.",
    },
    {
      id: "VII-4", grade: "VII", semester: "Gasal", number: 4, allocation: 6,
      element: "Fikih",
      title: "Mengagungkan Allah Subhanahu Wata'ala dengan Tunduk pada Perintah-Nya",
      overview: "Sujud syukur, sujud sahwi, dan sujud tilawah mengajarkan kerendahan hati. Ketiganya memiliki sebab dan tata cara berbeda, tetapi sama-sama menunjukkan ketundukan kepada Allah Subhanahu Wata'ala.",
      objectives: ["Membedakan tiga macam sujud", "Menjelaskan sebab dan tata caranya", "Menunjukkan sikap syukur serta rendah hati"],
      concepts: [
        ["Sujud syukur", "Sujud syukur dilakukan sebagai ungkapan terima kasih atas nikmat atau terhindar dari bahaya. Syukur juga diwujudkan melalui penggunaan nikmat secara benar dan berbagi kebaikan."],
        ["Sujud sahwi", "Sujud sahwi berkaitan dengan kelupaan tertentu dalam sholat. Pembahasannya melatih ketelitian terhadap urutan ibadah dan kesadaran bahwa manusia dapat lupa."],
        ["Sujud tilawah", "Sujud tilawah dilakukan ketika membaca atau mendengar ayat sajdah sesuai ketentuannya. Pelaksanaannya meneguhkan respons seorang mukmin terhadap ayat kebesaran Allah Subhanahu Wata'ala."],
        ["Nilai ketundukan", "Sujud mengingatkan bahwa kecerdasan, prestasi, dan kekuatan adalah amanah. Kerendahan hati tidak berarti lemah, melainkan mampu menggunakan kemampuan tanpa kesombongan."],
      ],
      applications: ["Mengucapkan syukur dan menggunakan keberhasilan untuk membantu", "Mengakui kesalahan tanpa mencari alasan", "Tidak merendahkan teman ketika memperoleh prestasi"],
      questions: ["Apa perbedaan sebab sujud syukur, sahwi, dan tilawah?", "Mengapa syukur harus diikuti tindakan?", "Bagaimana kerendahan hati terlihat dalam kehidupan sekolah?"],
      project: "Buat infografis perbandingan tiga macam sujud lengkap dengan sebab, waktu, dan hikmahnya.",
    },
    {
      id: "VII-5", grade: "VII", semester: "Gasal", number: 5, allocation: 9,
      element: "Sejarah Peradaban Islam",
      title: "Damaskus: Pusat Peradaban Timur Islam",
      overview: "Daulah Umayyah di Damaskus menjadi salah satu fase penting dalam perkembangan wilayah, administrasi, ilmu, arsitektur, dan kebudayaan Islam. Sejarah dipelajari secara kritis agar murid mampu mengambil ibrah, bukan sekedar menghafal nama dan tahun.",
      objectives: ["Menjelaskan lahir dan berkembangnya Daulah Umayyah", "Mengidentifikasi kemajuan peradaban", "Mengambil ibrah dari keberhasilan dan tantangannya"],
      concepts: [
        ["Latar sejarah", "Daulah Umayyah berpusat di Damaskus dan berkembang dalam konteks politik yang kompleks. Memahami konteks membantu murid menghindari penilaian sejarah yang terlalu sederhana."],
        ["Administrasi dan wilayah", "Pengelolaan pemerintahan, penggunaan bahasa Arab dalam administrasi, mata uang, serta layanan pos membantu penyatuan wilayah yang luas. Kemajuan memerlukan tata kelola yang tertib."],
        ["Ilmu dan arsitektur", "Perkembangan masjid, kota, penerjemahan awal, dan pusat-pusat ilmu menunjukkan perhatian terhadap peradaban. Bangunan juga merekam nilai, teknologi, dan keadaan masyarakat pada zamannya."],
        ["Ibrah kepemimpinan", "Keberhasilan dipengaruhi visi, organisasi, dan pelayanan; kemunduran dipengaruhi konflik serta ketidakadilan. Sejarah mengajarkan pentingnya persatuan, koreksi, dan tanggung jawab pemimpin."],
      ],
      applications: ["Membagi peran kelompok dengan tertib", "Mendokumentasikan kegiatan kelas", "Menyelesaikan perbedaan melalui musyawarah"],
      questions: ["Mengapa administrasi penting bagi wilayah yang luas?", "Apa hubungan ilmu dan kemajuan peradaban?", "Ibrah apa yang relevan bagi organisasi murid?"],
      project: "Susun lini masa visual Daulah Umayyah di Damaskus yang memisahkan fakta, analisis, dan ibrah.",
    },
    {
      id: "VII-6", grade: "VII", semester: "Genap", number: 6, allocation: 9,
      element: "Al Qur'an dan Hadits",
      title: "Alam Semesta sebagai Tanda Kekuasaan Allah Subhanahu Wata'ala",
      overview: "Keteraturan alam mendorong manusia berpikir, bersyukur, dan bertanggung jawab. Mengamati ciptaan Allah Subhanahu Wata'ala tidak menggantikan kajian ilmiah, tetapi memberikan landasan nilai agar ilmu digunakan untuk kemaslahatan.",
      objectives: ["Menghubungkan ayat kauniyah dengan pengamatan ilmiah", "Menjelaskan tanggung jawab manusia terhadap alam", "Merancang tindakan pelestarian sederhana"],
      concepts: [
        ["Ayat kauniyah", "Fenomena langit, bumi, air, tumbuhan, dan kehidupan merupakan tanda yang dapat direnungkan. Pengamatan yang teliti membangun kekaguman sekaligus kesadaran akan keterbatasan manusia."],
        ["Ilmu dan iman", "Islam mendorong penggunaan akal, bukti, dan proses belajar. Iman memberi orientasi moral agar pengetahuan tidak dipakai untuk merusak atau menindas."],
        ["Keseimbangan ekosistem", "Makhluk hidup saling bergantung dalam sebuah sistem. Kerusakan pada satu bagian dapat memengaruhi bagian lain sehingga pemanfaatan sumber daya perlu mempertimbangkan keberlanjutan."],
        ["Amanah menjaga bumi", "Menghemat air, mengurangi sampah, merawat tanaman, dan mencegah pencemaran merupakan bentuk tanggung jawab yang dapat dimulai dari lingkungan terdekat."],
      ],
      applications: ["Membawa wadah pakai ulang", "Mencatat penggunaan air dan listrik", "Melakukan pemilahan sampah di kelas"],
      questions: ["Bagaimana ilmu memperkuat rasa syukur?", "Mengapa kerusakan kecil dapat memengaruhi ekosistem?", "Tentukan satu masalah lingkungan sekolah dan kemungkinan solusinya."],
      project: "Lakukan audit sampah kelas selama tiga hari lalu susun rekomendasi pengurangan yang terukur.",
    },
    {
      id: "VII-7", grade: "VII", semester: "Genap", number: 7, allocation: 6,
      element: "Akhlak",
      title: "Mawas Diri dan Introspeksi dalam Menjalani Kehidupan",
      overview: "Muhasabah adalah kebiasaan menilai niat, proses, dan dampak perbuatan untuk melakukan perbaikan. Mawas diri tidak sama dengan menyalahkan diri, melainkan keberanian mengakui kekurangan dan menyusun langkah yang realistis.",
      objectives: ["Menjelaskan pengertian muhasabah", "Membedakan refleksi sehat dan menyalahkan diri", "Menyusun rencana perbaikan perilaku"],
      concepts: [
        ["Makna muhasabah", "Muhasabah menilai apakah tindakan sesuai nilai kebaikan. Penilaian dilakukan dengan jujur, tenang, dan diarahkan pada perbaikan."],
        ["Niat, proses, dan dampak", "Perbuatan tidak cukup dinilai dari hasil. Niat perlu diluruskan, proses harus benar, dan dampaknya terhadap diri serta orang lain perlu dipertimbangkan."],
        ["Mengakui kesalahan", "Pengakuan kesalahan membuka jalan meminta maaf, memperbaiki kerugian, dan mencegah pengulangan. Menutupi kesalahan justru memperbesar masalah."],
        ["Rencana perbaikan", "Perubahan efektif dimulai dari sasaran kecil, indikator jelas, dukungan lingkungan, dan evaluasi berkala. Kegagalan sementara dipakai sebagai data untuk memperbaiki strategi."],
      ],
      applications: ["Menulis refleksi belajar mingguan", "Meminta umpan balik dengan sopan", "Mengubah satu kebiasaan melalui target bertahap"],
      questions: ["Mengapa muhasabah bukan menyalahkan diri?", "Bagaimana menilai dampak sebuah tindakan?", "Tuliskan contoh target perbaikan yang terukur."],
      project: "Susun lembar muhasabah empat kolom: kejadian, nilai yang diuji, perbaikan, dan bukti kemajuan.",
    },
    {
      id: "VII-8", grade: "VII", semester: "Genap", number: 8, allocation: 9,
      element: "Akhlak",
      title: "Menghindari Ghibah dan Melaksanakan Tabayun",
      overview: "Ghibah merusak kehormatan dan kepercayaan, sedangkan tabayun melindungi masyarakat dari kesimpulan terburu-buru. Di ruang digital, keduanya berkaitan dengan jejak digital, manipulasi informasi, dan tanggung jawab berbagi.",
      objectives: ["Menjelaskan ghibah, fitnah, dan tabayun", "Menganalisis risiko penyebaran informasi", "Mempraktikkan verifikasi sederhana"],
      concepts: [
        ["Ghibah dan kehormatan", "Ghibah membicarakan keburukan seseorang yang tidak ia sukai walaupun hal itu benar. Apabila isinya tidak benar, kerusakannya bertambah karena mengandung kebohongan atau fitnah."],
        ["Tabayun", "Tabayun berarti mencari kejelasan melalui sumber yang layak, konteks yang lengkap, dan sikap adil. Tabayun bukan mencari pembenaran bagi prasangka."],
        ["Literasi digital", "Judul provokatif, gambar lama, potongan video, akun palsu, dan pesan berantai dapat menyesatkan. Tanggal, sumber, konteks, dan perbandingan dengan informasi terpercaya perlu diperiksa."],
        ["Memulihkan keadaan", "Jika terlanjur menyebarkan informasi salah, seseorang perlu menghentikan penyebaran, mengoreksi pada pihak yang sama, meminta maaf, dan belajar dari kesalahan."],
      ],
      applications: ["Menahan diri sebelum meneruskan pesan", "Menanyakan langsung secara santun", "Tidak menjadikan aib teman sebagai bahan candaan"],
      questions: ["Apa perbedaan ghibah dan kritik yang bertanggung jawab?", "Tuliskan empat langkah tabayun digital.", "Apa yang harus dilakukan setelah membagikan informasi salah?"],
      project: "Analisis satu contoh pesan berantai fiktif menggunakan cek sumber, tanggal, bukti, konteks, dan dampak.",
    },
    {
      id: "VII-9", grade: "VII", semester: "Genap", number: 9, allocation: 9,
      element: "Fikih",
      title: "Rukhsah: Kemudahan dari Allah Subhanahu Wata'ala dalam Beribadah",
      overview: "Rukhsah adalah keringanan syariat dalam kondisi tertentu. Ia menunjukkan kasih sayang dan keluwesan ajaran Islam, tetapi digunakan berdasarkan sebab serta ketentuan, bukan untuk meremehkan ibadah.",
      objectives: ["Menjelaskan makna rukhsah", "Mengidentifikasi contoh dan sebabnya", "Menentukan sikap yang bertanggung jawab"],
      concepts: [
        ["Pengertian rukhsah", "Rukhsah diberikan ketika terdapat keadaan yang diakui syariat, seperti perjalanan, sakit, atau kesulitan tertentu. Tujuannya menjaga pelaksanaan agama tanpa menimbulkan mudarat yang tidak perlu."],
        ["Contoh keringanan", "Jamak dan qasar, tayamum, tidak berpuasa bagi kondisi tertentu, serta bentuk lain memiliki syarat berbeda. Setiap contoh perlu dipelajari bersama ketentuan yang tepat."],
        ["Azimah dan rukhsah", "Azimah adalah hukum asal, sedangkan rukhsah merupakan keringanan karena sebab. Memilihnya memerlukan pemahaman keadaan, bukan semata-mata mencari yang paling mudah."],
        ["Tanggung jawab bertanya", "Persoalan kesehatan dan kondisi khusus sebaiknya dibicarakan dengan orang tua, guru agama, serta tenaga kesehatan bila relevan. Informasi singkat di media sosial tidak cukup untuk keputusan penting."],
      ],
      applications: ["Menyiapkan pengetahuan ibadah ketika bepergian", "Tidak mengejek orang yang menjalankan keringanan secara benar", "Bertanya ketika ragu terhadap syarat rukhsah"],
      questions: ["Mengapa rukhsah bukan berarti meremehkan ibadah?", "Apa perbedaan azimah dan rukhsah?", "Bagaimana mengambil keputusan ketika kondisi kesehatan memengaruhi ibadah?"],
      project: "Buat bagan keputusan sederhana tentang bersuci ketika air tidak tersedia atau berbahaya digunakan.",
    },
    {
      id: "VII-10", grade: "VII", semester: "Genap", number: 10, allocation: 9,
      element: "Sejarah Peradaban Islam",
      title: "Andalusia: Kota Peradaban Islam di Barat",
      overview: "Peradaban Islam di Andalusia memperlihatkan perkembangan ilmu, kota, seni, pertanian, dan kehidupan sosial. Kemajuan tersebut lahir dari kerja ilmu dan tata kelola, sedangkan konflik internal memberi pelajaran tentang pentingnya persatuan.",
      objectives: ["Menjelaskan perkembangan Islam di Andalusia", "Mengidentifikasi kontribusi ilmu dan budaya", "Mengambil ibrah secara kritis"],
      concepts: [
        ["Masuk dan berkembang", "Islam berkembang di Semenanjung Iberia dalam dinamika politik serta masyarakat yang beragam. Kota-kota seperti Cordoba menjadi pusat pemerintahan dan pembelajaran."],
        ["Ilmu pengetahuan", "Perpustakaan, pendidikan, kedokteran, filsafat, astronomi, dan ilmu terapan berkembang melalui tradisi membaca, meneliti, menerjemahkan, dan berdiskusi."],
        ["Kota dan kebudayaan", "Pengairan, pertanian, arsitektur, kebersihan kota, seni, dan kerajinan menunjukkan bahwa peradaban dibangun oleh banyak bidang yang saling mendukung."],
        ["Pelajaran kemunduran", "Perpecahan politik, perebutan kekuasaan, dan melemahnya persatuan mengurangi ketahanan. Kemajuan perlu dijaga melalui keadilan, ilmu, dan kepentingan bersama."],
      ],
      applications: ["Membangun sudut baca kelas", "Menghargai kontribusi berbagai kelompok", "Menjaga persatuan ketika berbeda pendapat"],
      questions: ["Apa syarat terbentuknya pusat ilmu?", "Mengapa kemajuan tidak hanya diukur dari bangunan?", "Pelajaran apa yang dapat diterapkan pada kelompok belajar?"],
      project: "Buat tur virtual berbentuk poster tentang satu kota Andalusia: lokasi, ilmu, budaya, dan ibrah.",
    },
    {
      id: "VIII-1", grade: "VIII", semester: "Gasal", number: 1, allocation: 9,
      element: "Al Qur'an dan Hadits",
      title: "Inspirasi Al Qur'an: Melestarikan Alam dan Menjaga Kehidupan",
      overview: "Al Qur'an membimbing manusia memanfaatkan alam secara bertanggung jawab dan melarang kerusakan. Pelestarian lingkungan merupakan bentuk syukur, amanah, dan perlindungan terhadap kehidupan.",
      objectives: ["Menganalisis pesan ayat tentang alam", "Menjelaskan manusia sebagai khalifah", "Menyusun aksi lingkungan berbasis data"],
      concepts: [
        ["Khalifah dan amanah", "Manusia diberi kemampuan mengelola bumi, bukan hak untuk mengeksploitasinya tanpa batas. Kekuasaan selalu disertai tanggung jawab kepada Allah Subhanahu Wata'ala dan sesama makhluk."],
        ["Larangan berbuat kerusakan", "Kerusakan dapat berbentuk pencemaran, pemborosan, perusakan habitat, dan perilaku yang mengancam kesehatan. Dampaknya sering dirasakan kelompok yang tidak ikut menikmati keuntungan."],
        ["Keseimbangan", "Alam bekerja melalui keterkaitan dan ukuran. Prinsip keseimbangan mendorong penggunaan sumber daya secukupnya serta pemulihan terhadap bagian yang telah rusak."],
        ["Aksi berbasis data", "Kepedulian perlu diterjemahkan menjadi tindakan terukur: mengenali masalah, mengumpulkan data, menentukan prioritas, melakukan aksi, dan mengevaluasi hasil."],
      ],
      applications: ["Mengukur sampah harian", "Mengurangi plastik sekali pakai", "Merawat tanaman dan saluran air sekolah"],
      questions: ["Apa perbedaan mengelola dan mengeksploitasi alam?", "Mengapa aksi lingkungan memerlukan data?", "Siapa yang paling terdampak jika air tercemar?"],
      project: "Rancang aksi 'Sekolah Minim Sampah' dengan target, pembagian tugas, bukti, dan evaluasi.",
    },
    {
      id: "VIII-2", grade: "VIII", semester: "Gasal", number: 2, allocation: 6,
      element: "Akidah",
      title: "Iman kepada Kitab-Kitab Allah Subhanahu Wata'ala",
      overview: "Beriman kepada kitab-kitab Allah Subhanahu Wata'ala berarti meyakini bahwa wahyu diturunkan sebagai petunjuk. Seorang Muslim mencintai Al Qur'an, menghormati kitab yang diturunkan sebelumnya, dan menjaga adab dalam perbedaan.",
      objectives: ["Menjelaskan makna iman kepada kitab", "Membedakan kitab dan suhuf", "Menunjukkan adab terhadap Al Qur'an dan perbedaan"],
      concepts: [
        ["Wahyu sebagai petunjuk", "Allah Subhanahu Wata'ala menurunkan petunjuk kepada para rasul agar manusia mengenal kebenaran dan menjalani kehidupan dengan nilai yang benar."],
        ["Kitab dan rasul penerima", "Taurat diturunkan kepada Nabi Musa 'Alaihissalam, Zabur kepada Nabi Dawud 'Alaihissalam, Injil kepada Nabi Isa 'Alaihissalam, dan Al Qur'an kepada Nabi Muhammad Sholallohu 'Alaihi Wasallam."],
        ["Kitab dan suhuf", "Kitab dan suhuf sama-sama wahyu, tetapi dipahami memiliki bentuk serta cakupan yang berbeda. Inti ajaran para rasul mengajak kepada tauhid dan ketaatan kepada Allah Subhanahu Wata'ala."],
        ["Mencintai Al Qur'an", "Cinta diwujudkan dengan membaca secara benar, memahami, mengamalkan, menjaga kehormatan, dan tidak menggunakan ayat untuk membenarkan kebencian atau kepentingan pribadi."],
      ],
      applications: ["Membaca Al Qur'an secara teratur", "Menjaga mushaf dengan hormat", "Berdialog tanpa merendahkan kitab atau keyakinan lain"],
      questions: ["Apa makna iman kepada kitab Allah Subhanahu Wata'ala?", "Bagaimana wujud cinta kepada Al Qur'an selain membaca?", "Mengapa penghormatan tidak berarti mencampuradukkan akidah?"],
      project: "Buat poster 'Cinta Al Qur'an' yang memuat adab membaca, memahami, mengamalkan, dan menjaga.",
    },
    {
      id: "VIII-3", grade: "VIII", semester: "Gasal", number: 3, allocation: 9,
      element: "Akhlak",
      title: "Amanah dan Jujur dalam Kehidupan",
      overview: "Amanah berarti dapat dipercaya dalam menunaikan tanggung jawab, sedangkan jujur berarti selaras antara fakta, ucapan, dan tindakan. Keduanya menjadi dasar kepercayaan di keluarga, sekolah, masyarakat, dan ruang digital.",
      objectives: ["Menjelaskan amanah dan jujur", "Menganalisis bentuk ketidakjujuran", "Membangun strategi menjaga integritas"],
      concepts: [
        ["Dimensi amanah", "Amanah mencakup tanggung jawab kepada Allah Subhanahu Wata'ala, diri sendiri, orang lain, lingkungan, dan tugas. Menjaga waktu serta fasilitas juga termasuk amanah."],
        ["Kejujuran akademik", "Menyontek, plagiarisme, memalsukan data, dan menyerahkan karya AI tanpa pemeriksaan melanggar integritas. Teknologi boleh membantu, tetapi sumber serta proses perlu diakui."],
        ["Dampak kepercayaan", "Satu kebohongan dapat menuntut kebohongan lain dan merusak kerja sama. Kejujuran mungkin memiliki konsekuensi, tetapi memungkinkan masalah diperbaiki secara adil."],
        ["Menguatkan integritas", "Integritas dilatih melalui aturan diri, dokumentasi sumber, keberanian mengatakan belum tahu, dan kesediaan bertanggung jawab ketika melakukan kesalahan."],
      ],
      applications: ["Mencantumkan sumber karya", "Mengembalikan barang temuan", "Melaporkan hasil pengamatan apa adanya"],
      questions: ["Apa perbedaan amanah dan jujur?", "Mengapa plagiarisme merusak proses belajar?", "Bagaimana menggunakan AI secara etis untuk tugas?"],
      project: "Susun piagam integritas kelas yang berisi hak, kewajiban, dan cara memulihkan pelanggaran.",
    },
    {
      id: "VIII-4", grade: "VIII", semester: "Gasal", number: 4, allocation: 9,
      element: "Fikih",
      title: "Sholat Gerhana, Istiska, dan Jenazah",
      overview: "Tiga ibadah ini menghubungkan ketundukan kepada Allah Subhanahu Wata'ala dengan kepedulian sosial serta perenungan terhadap alam dan kehidupan. Masing-masing memiliki sebab, hukum, dan tata cara yang perlu dipelajari dengan tertib.",
      objectives: ["Membedakan ketentuan tiga sholat", "Mempraktikkan bagian tata cara melalui simulasi", "Menjelaskan nilai sosial dan spiritual"],
      concepts: [
        ["Sholat gerhana", "Sholat gerhana dilaksanakan ketika terjadi gerhana matahari atau bulan. Ibadah ini mengarahkan manusia mengagungkan Pencipta, bukan mengaitkan gerhana dengan mitos atau kematian seseorang."],
        ["Sholat istiska", "Sholat istiska merupakan permohonan hujan ketika terjadi kekeringan. Ia disertai introspeksi, doa, dan tanggung jawab memperbaiki pengelolaan air serta lingkungan."],
        ["Sholat jenazah", "Sholat jenazah adalah kewajiban kolektif dengan rangkaian takbir dan doa tanpa rukuk serta sujud. Ibadah ini merupakan penghormatan terakhir dan dukungan bagi keluarga yang berduka."],
        ["Nilai kepedulian", "Ketiganya mengajarkan tauhid, penolakan takhayul, solidaritas, kepedulian lingkungan, ingat kematian, dan tanggung jawab bersama."],
      ],
      applications: ["Tidak menyebarkan mitos gerhana", "Menghemat air saat kemarau", "Menyampaikan takziah dengan empati"],
      questions: ["Apa perbedaan struktur sholat jenazah dan sholat biasa?", "Mengapa istiska perlu disertai perbaikan lingkungan?", "Nilai apa yang dapat dipelajari dari gerhana?"],
      project: "Buat tabel perbandingan hukum, sebab, waktu, tata cara ringkas, dan hikmah ketiga sholat.",
    },
    {
      id: "VIII-5", grade: "VIII", semester: "Gasal", number: 5, allocation: 9,
      element: "Sejarah Peradaban Islam",
      title: "Semangat Literasi pada Masa Daulah Abbasiyah",
      overview: "Masa Abbasiyah dikenal dengan berkembangnya ilmu melalui lembaga pendidikan, perpustakaan, penerjemahan, observasi, dan dialog. Kemajuan lahir dari ekosistem yang menghargai pembaca, penulis, peneliti, dan dukungan kelembagaan.",
      objectives: ["Menjelaskan perkembangan literasi Abbasiyah", "Mengidentifikasi faktor kemajuan ilmu", "Menerapkan budaya literasi di sekolah"],
      concepts: [
        ["Pusat ilmu", "Baghdad berkembang sebagai pusat politik dan intelektual. Perpustakaan, majelis ilmu, rumah sakit, serta lembaga penerjemahan mempertemukan berbagai pengetahuan."],
        ["Gerakan penerjemahan", "Karya dari beragam bahasa diterjemahkan, dikaji, dikritik, dan dikembangkan. Penerjemahan bukan menyalin pasif, tetapi pintu menuju penelitian baru."],
        ["Tradisi ilmiah", "Ilmuwan menggunakan pengamatan, perhitungan, penalaran, dan penulisan. Perbedaan gagasan dapat menjadi sumber kemajuan ketika dibahas dengan adab serta bukti."],
        ["Ekosistem literasi", "Kemajuan membutuhkan akses bacaan, guru, waktu belajar, penghargaan terhadap karya, dan kebebasan bertanya yang bertanggung jawab."],
      ],
      applications: ["Mencatat sumber bacaan", "Membuat ulasan buku", "Membangun forum diskusi berbasis bukti"],
      questions: ["Mengapa penerjemahan mendorong inovasi?", "Apa unsur ekosistem literasi?", "Bagaimana membedakan pendapat dan bukti?"],
      project: "Rancang program '15 Menit Literasi PAIBP' selama satu bulan lengkap dengan produk dan evaluasi.",
    },
    {
      id: "VIII-6", grade: "VIII", semester: "Genap", number: 6, allocation: 9,
      element: "Al Qur'an dan Hadits",
      title: "Indahnya Beragama Secara Moderat",
      overview: "Moderasi beragama berarti menjalankan ajaran secara teguh, adil, seimbang, dan tidak berlebihan. Sikap ini menolak kekerasan serta kebencian, sekaligus menjaga komitmen terhadap ajaran agama.",
      objectives: ["Menjelaskan makna moderasi beragama", "Membedakan teguh dan ekstrem", "Menerapkan sikap adil dalam perbedaan"],
      concepts: [
        ["Adil dan seimbang", "Adil berarti menempatkan sesuatu secara proporsional dan memenuhi hak. Seimbang menghindarkan manusia dari sikap meremehkan maupun berlebihan."],
        ["Teguh tanpa memaksa", "Keyakinan dapat dijaga dengan kuat tanpa memaksa, menghina, atau mengganggu hak orang lain. Keteguhan diuji melalui akhlak ketika berhadapan dengan perbedaan."],
        ["Anti-kekerasan", "Kekerasan verbal, fisik, dan digital tidak dapat dibenarkan untuk memenangkan pendapat. Perselisihan diselesaikan melalui aturan, dialog, dan pihak yang berwenang."],
        ["Konteks kebangsaan", "Muslim menjalankan ajaran sekaligus menjaga persatuan, menaati aturan yang adil, menghormati keragaman, dan bekerja sama dalam kemaslahatan."],
      ],
      applications: ["Tidak mengejek praktik yang berbeda", "Menyampaikan pendapat dengan data", "Bekerja sama dalam kegiatan sosial"],
      questions: ["Apa perbedaan moderat dan tidak teguh?", "Bagaimana menyikapi perbedaan fikih?", "Mengapa kekerasan merusak tujuan dakwah?"],
      project: "Analisis tiga situasi perbedaan dan susun respons yang teguh, santun, adil, serta damai.",
    },
    {
      id: "VIII-7", grade: "VIII", semester: "Genap", number: 7, allocation: 6,
      element: "Akidah",
      title: "Iman kepada Nabi dan Rasul Allah Subhanahu Wata'ala",
      overview: "Nabi dan rasul menerima bimbingan dari Allah Subhanahu Wata'ala serta menjadi teladan bagi umat. Iman kepada mereka diwujudkan dengan keyakinan, penghormatan, mempelajari perjuangan, dan meneladani sifat mulia.",
      objectives: ["Menjelaskan nabi dan rasul", "Menguraikan sifat wajib serta mustahil rasul", "Meneladani sifat rasul dalam kehidupan digital"],
      concepts: [
        ["Nabi dan rasul", "Keduanya adalah manusia pilihan yang menerima wahyu. Para rasul memiliki tugas menyampaikan risalah kepada umat sesuai kehendak Allah Subhanahu Wata'ala."],
        ["Siddiq dan amanah", "Siddiq berarti benar, sedangkan amanah berarti dapat dipercaya. Keteladanan ini relevan dalam berbicara, belajar, memegang rahasia, dan menggunakan teknologi."],
        ["Tabligh dan fathanah", "Tabligh berarti menyampaikan risalah dan fathanah berarti cerdas. Komunikasi yang baik memerlukan isi benar, cara tepat, pemahaman konteks, dan pertimbangan dampak."],
        ["Meneladani secara nyata", "Cinta kepada rasul tidak berhenti pada pengetahuan nama. Ia terlihat melalui akhlak, kesungguhan belajar, kasih sayang, keberanian membela kebenaran, dan pelayanan."],
      ],
      applications: ["Tidak membuat identitas palsu", "Menyampaikan informasi dengan bahasa santun", "Menggunakan kecerdasan untuk memecahkan masalah"],
      questions: ["Mengapa rasul harus memiliki sifat amanah?", "Bagaimana tabligh diterapkan di media sosial?", "Berikan contoh fathanah yang berorientasi maslahat."],
      project: "Buat profil keteladanan satu rasul dan hubungkan empat sifat utama dengan tantangan murid masa kini.",
    },
    {
      id: "VIII-8", grade: "VIII", semester: "Genap", number: 8, allocation: 9,
      element: "Akhlak",
      title: "Toleransi dan Harmoni Antarumat Beragama",
      overview: "Toleransi adalah penghormatan terhadap hak dan martabat orang lain dalam perbedaan. Toleransi tidak mencampuradukkan akidah, tetapi memungkinkan kerja sama, dialog, dan kehidupan damai.",
      objectives: ["Menjelaskan batas dan bentuk toleransi", "Menganalisis konflik karena prasangka", "Membangun dialog yang saling menghormati"],
      concepts: [
        ["Martabat manusia", "Setiap manusia perlu diperlakukan secara adil dan bermartabat. Perbedaan identitas tidak membenarkan penghinaan, perundungan, atau pengurangan hak."],
        ["Batas toleransi", "Toleransi diberikan dalam hubungan sosial, kemanusiaan, dan kebangsaan tanpa mengikuti ibadah atau mencampurkan keyakinan yang tidak sesuai dengan akidah."],
        ["Prasangka dan stereotip", "Penilaian terhadap seluruh kelompok berdasarkan satu pengalaman melahirkan ketidakadilan. Informasi perlu diperiksa dan individu dinilai berdasarkan perilakunya."],
        ["Kerja sama sosial", "Gotong royong dalam kebersihan, kebencanaan, kesehatan, dan kemanusiaan dapat memperkuat harmoni tanpa menghilangkan identitas keagamaan."],
      ],
      applications: ["Menghormati waktu ibadah", "Tidak menggunakan julukan merendahkan", "Bekerja sama dalam kegiatan kemanusiaan"],
      questions: ["Apa batas toleransi dalam akidah?", "Bagaimana stereotip menimbulkan ketidakadilan?", "Susun kalimat respons terhadap candaan yang merendahkan agama."],
      project: "Buat panduan kelas harmonis yang memuat bahasa inklusif, cara dialog, dan penyelesaian konflik.",
    },
    {
      id: "VIII-9", grade: "VIII", semester: "Genap", number: 9, allocation: 9,
      element: "Fikih",
      title: "Muamalah: Jual Beli, Utang Piutang, dan Menjauhi Riba",
      overview: "Muamalah mengatur hubungan ekonomi agar berlangsung sukarela, transparan, adil, dan bebas dari kezaliman. Pemahaman ini penting dalam transaksi tunai, daring, pinjaman, serta penggunaan layanan digital.",
      objectives: ["Menjelaskan prinsip jual beli", "Menganalisis etika utang piutang", "Mengidentifikasi praktik riba dan transaksi merugikan"],
      concepts: [
        ["Jual beli yang adil", "Penjual dan pembeli harus mengetahui barang, harga, kondisi, dan kesepakatan. Penipuan kualitas, pengurangan ukuran, serta informasi palsu merusak kerelaan."],
        ["Utang piutang", "Utang adalah amanah yang perlu dicatat, memiliki kesepakatan jelas, dan dibayar sesuai kemampuan serta waktu. Pemberi utang dianjurkan tidak mempermalukan pihak yang kesulitan."],
        ["Riba", "Riba berkaitan dengan tambahan yang dilarang dalam transaksi tertentu karena mengandung ketidakadilan. Pembahasan kasus modern perlu kehati-hatian dan rujukan kepada pihak yang kompeten."],
        ["Transaksi digital", "Belanja daring memerlukan pemeriksaan toko, ulasan, harga, biaya tersembunyi, keamanan pembayaran, dan kebutuhan nyata. Kemudahan kredit tidak boleh mendorong konsumsi tanpa perhitungan."],
      ],
      applications: ["Mencatat pinjaman barang atau uang", "Jujur menjelaskan kondisi barang", "Membandingkan kebutuhan dan kemampuan sebelum membeli"],
      questions: ["Mengapa kejelasan informasi penting dalam jual beli?", "Apa adab orang berutang dan pemberi utang?", "Risiko apa yang perlu diperiksa dalam transaksi digital?"],
      project: "Analisis simulasi toko daring berdasarkan kejujuran informasi, harga, hak pembeli, dan risiko pembayaran.",
    },
    {
      id: "VIII-10", grade: "VIII", semester: "Genap", number: 10, allocation: 9,
      element: "Sejarah Peradaban Islam",
      title: "Ilmuwan Muslim pada Masa Daulah Abbasiyah",
      overview: "Ilmuwan Muslim mengembangkan pengetahuan melalui pembacaan, observasi, perhitungan, eksperimen, penulisan, dan kritik. Kontribusi mereka perlu dipahami berdasarkan bidang serta karya, bukan sekedar daftar nama.",
      objectives: ["Mengidentifikasi ilmuwan dan kontribusinya", "Menjelaskan etos ilmiah", "Meneladani integritas dalam penelitian sederhana"],
      concepts: [
        ["Al-Khawarizmi dan matematika", "Karya Al-Khawarizmi berpengaruh pada perkembangan aljabar dan metode perhitungan. Matematika membantu manusia menjelaskan pola serta menyelesaikan persoalan nyata."],
        ["Ibnu Sina dan kedokteran", "Ibnu Sina dikenal melalui karya kedokteran dan pemikiran sistematis. Ilmu kesehatan berkembang melalui pengamatan, dokumentasi, dan pembelajaran dari pengalaman sebelumnya."],
        ["Ibnu Al-Haitsam dan optika", "Kajian tentang cahaya serta penglihatan menunjukkan pentingnya pengujian terhadap dugaan. Pengetahuan tidak cukup berdasarkan pendapat tanpa bukti."],
        ["Etos ilmiah", "Rasa ingin tahu, ketekunan, keterbukaan terhadap koreksi, pencatatan sumber, dan orientasi manfaat merupakan teladan yang relevan bagi murid."],
      ],
      applications: ["Mencatat langkah percobaan", "Membedakan data dan opini", "Mengakui sumber serta bantuan"],
      questions: ["Apa hubungan metode dan keandalan pengetahuan?", "Mengapa kesalahan perlu dicatat?", "Bagaimana integritas ilmiah diterapkan dalam tugas sekolah?"],
      project: "Buat pameran mini profil ilmuwan Muslim berisi masalah, metode, karya, pengaruh, dan nilai teladannya.",
    },
    {
      id: "IX-1", grade: "IX", semester: "Gasal", number: 1, allocation: 9,
      element: "Al Qur'an dan Hadits",
      title: "Al Qur'an Menginspirasi: Semangat Mencari Ilmu",
      overview: "Mencari ilmu merupakan jalan memuliakan manusia dan menghadirkan manfaat. Al Qur'an mengarahkan kegiatan belajar agar disertai iman, adab, penalaran, dan tanggung jawab.",
      objectives: ["Menganalisis pesan dalil tentang ilmu", "Menjelaskan adab mencari ilmu", "Menyusun strategi belajar berkelanjutan"],
      concepts: [
        ["Kemuliaan ilmu", "Ilmu membantu manusia mengenal Allah Subhanahu Wata'ala, memahami kehidupan, dan mengambil keputusan. Kemuliaan tidak terletak pada gelar, tetapi pada kebenaran serta manfaat ilmu."],
        ["Adab belajar", "Niat, menghormati guru, bersungguh-sungguh, bertanya dengan santun, menjaga sumber, dan mengamalkan pengetahuan merupakan bagian dari proses mencari ilmu."],
        ["Literasi kritis", "Pembelajar memeriksa penulis, bukti, tanggal, tujuan, dan konteks informasi. Banyaknya konten tidak sama dengan kedalaman pengetahuan."],
        ["Belajar sepanjang hayat", "Kemampuan berubah dan persoalan baru muncul. Kebiasaan membaca, berlatih, mengevaluasi, dan meminta umpan balik membantu manusia terus berkembang."],
      ],
      applications: ["Membuat jadwal belajar realistis", "Menggunakan sumber tepercaya", "Mengajari teman tanpa merendahkan"],
      questions: ["Apa perbedaan informasi dan ilmu?", "Mengapa adab memengaruhi kebermanfaatan ilmu?", "Susun satu strategi mengatasi gangguan belajar."],
      project: "Buat kontrak belajar 30 hari dengan tujuan, kebiasaan kecil, bukti, dukungan, dan evaluasi.",
    },
    {
      id: "IX-2", grade: "IX", semester: "Gasal", number: 2, allocation: 9,
      element: "Akidah",
      title: "Iman kepada Hari Akhir dan Mawas Diri",
      overview: "Iman kepada Hari Akhir meneguhkan keyakinan bahwa kehidupan dunia memiliki tujuan dan setiap perbuatan dipertanggungjawabkan. Keyakinan ini melahirkan harapan, kehati-hatian, serta keberanian berbuat benar.",
      objectives: ["Menjelaskan makna dan tahapan Hari Akhir", "Membedakan kiamat sugra dan kubra", "Menghubungkan iman dengan tanggung jawab"],
      concepts: [
        ["Kehidupan dunia dan akhirat", "Dunia merupakan tempat beramal, sedangkan akhirat menjadi kehidupan pembalasan. Keduanya dipahami secara seimbang agar manusia tidak lalai maupun putus asa."],
        ["Kiamat sugra dan kubra", "Kiamat sugra berkaitan dengan berakhirnya kehidupan individu atau peristiwa terbatas, sedangkan kiamat kubra merupakan berakhirnya tatanan alam atas kehendak Allah Subhanahu Wata'ala."],
        ["Tahapan akhirat", "Pembahasan meliputi kematian, alam barzakh, kebangkitan, pengumpulan, perhitungan, penimbangan amal, dan balasan sesuai penjelasan ajaran Islam."],
        ["Dampak keimanan", "Iman kepada Hari Akhir menguatkan kejujuran, tanggung jawab, kesabaran, kepedulian, dan keberanian menolak kezaliman meskipun tidak dilihat orang lain."],
      ],
      applications: ["Berbuat jujur tanpa pengawasan", "Menyelesaikan tanggung jawab sebelum terlambat", "Menghindari konten ramalan kiamat tanpa dasar"],
      questions: ["Mengapa iman kepada Hari Akhir membangun tanggung jawab?", "Apa perbedaan kiamat sugra dan kubra?", "Bagaimana menanggapi ramalan tanggal kiamat?"],
      project: "Susun peta konsep tahapan kehidupan akhirat dan kaitkan setiap tahap dengan satu sikap positif.",
    },
    {
      id: "IX-3", grade: "IX", semester: "Gasal", number: 3, allocation: 9,
      element: "Akhlak",
      title: "Etika Pergaulan dan Komunikasi Islami",
      overview: "Pergaulan sehat menjaga martabat, batas, keselamatan, dan hak setiap orang. Komunikasi Islami menuntut kebenaran, kesantunan, empati, serta tanggung jawab terhadap dampak ucapan.",
      objectives: ["Menjelaskan prinsip pergaulan sehat", "Menganalisis komunikasi verbal dan digital", "Menerapkan batas serta persetujuan yang sehat"],
      concepts: [
        ["Martabat dan batas", "Setiap orang berhak merasa aman dan dihormati. Batas pergaulan membantu menjaga kehormatan, kesehatan, fokus belajar, dan mencegah tindakan yang merugikan."],
        ["Komunikasi santun", "Ucapan perlu benar, baik, jelas, dan sesuai situasi. Nada, waktu, ekspresi, dan saluran komunikasi dapat mengubah dampak pesan."],
        ["Persetujuan dan keselamatan", "Foto, data, cerita pribadi, dan sentuhan tidak boleh dipaksakan. Ketika merasa tidak aman, murid perlu menolak dengan tegas dan mencari bantuan orang dewasa tepercaya."],
        ["Jejak digital", "Pesan dan gambar dapat disalin, disebarkan, serta bertahan lama. Kendali diri sebelum mengunggah lebih mudah daripada memperbaiki kerusakan setelah tersebar."],
      ],
      applications: ["Meminta izin sebelum membagikan foto", "Menolak ajakan berisiko", "Menghentikan candaan ketika orang lain tidak nyaman"],
      questions: ["Mengapa niat baik belum tentu menghasilkan komunikasi baik?", "Bagaimana cara menolak dengan tegas dan santun?", "Apa langkah aman ketika mengalami perundungan digital?"],
      project: "Buat skenario percakapan untuk menyelesaikan salah paham tanpa mempermalukan pihak lain.",
    },
    {
      id: "IX-4", grade: "IX", semester: "Gasal", number: 4, allocation: 6,
      element: "Fikih",
      title: "Akikah dan Kurban sebagai Wujud Syukur dan Kepedulian",
      overview: "Akikah dan kurban merupakan ibadah yang memiliki ketentuan, waktu, serta tujuan berbeda. Keduanya menumbuhkan syukur, ketaatan, kepedulian, dan semangat berbagi.",
      objectives: ["Membedakan akikah dan kurban", "Menjelaskan ketentuan pokok", "Menganalisis nilai sosial pelaksanaannya"],
      concepts: [
        ["Makna akikah", "Akikah berkaitan dengan kelahiran anak sebagai ungkapan syukur dan mengikuti tuntunan. Pelaksanaannya disesuaikan dengan kemampuan serta ketentuan yang dipelajari."],
        ["Makna kurban", "Kurban dilaksanakan pada waktu tertentu sebagai bentuk ketaatan dan keteladanan pengorbanan Nabi Ibrahim 'Alaihissalam serta Nabi Ismail 'Alaihissalam."],
        ["Hewan dan pelaksanaan", "Jenis, usia, kondisi hewan, waktu penyembelihan, serta proses distribusi memiliki ketentuan. Kesejahteraan hewan, kebersihan, dan keamanan perlu dijaga."],
        ["Nilai sosial", "Daging dibagikan secara bermartabat dan tidak digunakan untuk pamer. Ibadah melatih kesediaan mengurangi kepentingan diri demi mendekatkan diri kepada Allah Subhanahu Wata'ala."],
      ],
      applications: ["Menghargai keluarga dengan kemampuan berbeda", "Membantu distribusi secara tertib", "Tidak mengunggah penerima bantuan tanpa izin"],
      questions: ["Apa perbedaan tujuan dan waktu akikah serta kurban?", "Mengapa distribusi harus menjaga martabat?", "Bagaimana nilai pengorbanan diterapkan oleh murid?"],
      project: "Susun alur panitia kurban sekolah yang aman, bersih, adil, dan menjaga martabat penerima.",
    },
    {
      id: "IX-5", grade: "IX", semester: "Gasal", number: 5, allocation: 9,
      element: "Sejarah Peradaban Islam",
      title: "Mengapresiasi Peradaban Daulah Usmani",
      overview: "Daulah Usmani bertahan dalam rentang panjang dan mengelola wilayah lintas kawasan. Kajian terhadap pemerintahan, militer, arsitektur, ilmu, dan perubahan zamannya memberikan pelajaran tentang adaptasi serta tata kelola.",
      objectives: ["Menjelaskan perkembangan Daulah Usmani", "Mengidentifikasi warisan peradaban", "Menganalisis faktor ketahanan dan kemunduran"],
      concepts: [
        ["Pertumbuhan wilayah", "Daulah Usmani berkembang dari kekuatan regional menjadi pemerintahan luas. Letak strategis dan organisasi berperan dalam hubungan perdagangan serta politik."],
        ["Konstantinopel", "Penaklukan Konstantinopel di bawah Sultan Muhammad Al-Fatih menjadi peristiwa penting. Keberhasilan melibatkan persiapan, strategi, teknologi, disiplin, dan kepemimpinan."],
        ["Tata kelola dan budaya", "Masjid, sekolah, rumah sakit, layanan sosial, seni kaligrafi, dan arsitektur menunjukkan hubungan antara negara, masyarakat, dan kebudayaan."],
        ["Adaptasi dan kemunduran", "Perubahan teknologi, ekonomi, politik internasional, serta persoalan internal menuntut pembaruan. Organisasi yang berhenti belajar akan kehilangan kemampuan menghadapi zaman."],
      ],
      applications: ["Membuat rencana sebelum bertindak", "Belajar dari teknologi baru", "Menjaga fasilitas publik"],
      questions: ["Faktor apa yang mendukung penaklukan Konstantinopel?", "Mengapa organisasi harus beradaptasi?", "Apa warisan Usmani yang masih dapat diamati?"],
      project: "Buat analisis kepemimpinan Muhammad Al-Fatih: visi, persiapan, strategi, risiko, dan ibrah.",
    },
    {
      id: "IX-6", grade: "IX", semester: "Genap", number: 6, allocation: 9,
      element: "Al Qur'an dan Hadits",
      title: "Menjadi Khalifah yang Menjaga Bumi",
      overview: "Khalifah berarti manusia menerima amanah mengelola kehidupan sesuai nilai Allah Subhanahu Wata'ala. Amanah itu mencakup keadilan, keberlanjutan, perlindungan makhluk, dan penggunaan teknologi secara bertanggung jawab.",
      objectives: ["Menganalisis tanggung jawab khalifah", "Menjelaskan keadilan antargenerasi", "Merancang solusi lingkungan kolaboratif"],
      concepts: [
        ["Amanah kekhalifahan", "Manusia memiliki daya pikir dan kemampuan mengubah lingkungan. Kemampuan tersebut harus diarahkan pada pemeliharaan, bukan kerusakan atau keuntungan sesaat."],
        ["Keadilan antargenerasi", "Sumber daya yang dipakai hari ini memengaruhi kehidupan masa depan. Generasi berikutnya berhak memperoleh lingkungan yang layak dan kesempatan hidup."],
        ["Teknologi dan etika", "Teknologi dapat menghemat sumber daya atau memperbesar kerusakan. Dampak, akses, limbah, energi, dan siapa yang menanggung risiko perlu dipertimbangkan."],
        ["Kolaborasi", "Masalah lingkungan melibatkan kebiasaan, aturan, fasilitas, ekonomi, dan budaya. Solusi berkelanjutan membutuhkan kerja sama sekolah, keluarga, pemerintah, serta masyarakat."],
      ],
      applications: ["Menghitung jejak sampah kegiatan", "Menggunakan teknologi hemat energi", "Mengajak pihak sekolah melalui proposal berbasis data"],
      questions: ["Apa arti keadilan antargenerasi?", "Bagaimana menilai dampak teknologi?", "Mengapa aksi pribadi dan kebijakan perlu berjalan bersama?"],
      project: "Susun proposal solusi satu masalah lingkungan sekolah dengan data, anggaran sederhana, indikator, dan mitra.",
    },
    {
      id: "IX-7", grade: "IX", semester: "Genap", number: 7, allocation: 9,
      element: "Akidah",
      title: "Iman kepada Qada dan Qadar",
      overview: "Iman kepada qada dan qadar membangun keseimbangan antara keyakinan terhadap ketetapan Allah Subhanahu Wata'ala dan tanggung jawab manusia untuk berikhtiar. Takdir tidak boleh dijadikan alasan untuk pasif atau menghindari tanggung jawab.",
      objectives: ["Menjelaskan qada dan qadar", "Menghubungkan ikhtiar, doa, dan tawakal", "Menunjukkan optimisme serta tanggung jawab"],
      concepts: [
        ["Qada dan qadar", "Keduanya berkaitan dengan ketetapan serta ukuran Allah Subhanahu Wata'ala atas ciptaan. Pembahasan dilakukan dengan rendah hati karena pengetahuan manusia terbatas."],
        ["Ikhtiar", "Manusia diperintahkan menggunakan kemampuan, ilmu, waktu, dan pilihan yang dimiliki. Hasil tidak selalu sesuai rencana, tetapi proses tetap harus dilakukan secara benar."],
        ["Doa dan tawakal", "Doa menunjukkan kebutuhan kepada Allah Subhanahu Wata'ala, sedangkan tawakal adalah menyerahkan hasil setelah ikhtiar yang layak, bukan menggantikan usaha."],
        ["Sikap menghadapi hasil", "Keberhasilan disyukuri tanpa sombong; kegagalan dievaluasi tanpa putus asa. Musibah dihadapi dengan sabar, mencari pertolongan, dan memperbaiki hal yang masih dapat diubah."],
      ],
      applications: ["Belajar terencana sebelum ujian", "Menerima hasil sambil mengevaluasi strategi", "Tidak menyalahkan takdir atas kelalaian"],
      questions: ["Mengapa tawakal harus didahului ikhtiar?", "Bagaimana iman kepada takdir membangun optimisme?", "Bedakan hal yang dapat dan tidak dapat dikendalikan."],
      project: "Buat lingkar kendali: hal yang dapat dikendalikan, dipengaruhi, dan diterima dalam satu masalah nyata.",
    },
    {
      id: "IX-8", grade: "IX", semester: "Genap", number: 8, allocation: 6,
      element: "Akhlak",
      title: "Seni Islami dan Kehidupan Harmonis",
      overview: "Seni merupakan ekspresi keindahan dan kreativitas yang perlu dijalankan secara bertanggung jawab. Seni Islami mengarahkan karya agar menjaga nilai kebaikan, martabat, kepantasan, dan kemaslahatan.",
      objectives: ["Menjelaskan hubungan Islam dan keindahan", "Menilai karya berdasarkan etika", "Menghasilkan karya kreatif yang bertanggung jawab"],
      concepts: [
        ["Keindahan dan nilai", "Keindahan dapat hadir dalam suara, bahasa, gerak, rupa, ruang, dan perilaku. Nilai sebuah karya tidak hanya ditentukan oleh tampilannya, tetapi juga pesan serta dampaknya."],
        ["Ragam seni Islami", "Kaligrafi, arsitektur, sastra, musik tradisi, dekorasi geometris, dan seni pertunjukan berkembang dalam konteks budaya yang beragam."],
        ["Etika berkarya", "Karya perlu menghormati hak cipta, tidak merendahkan kelompok, tidak mengeksploitasi tubuh atau penderitaan, dan tidak mengajak pada kerusakan."],
        ["Seni dan harmoni", "Seni dapat menjadi media pendidikan, dakwah, penyembuhan sosial, pelestarian budaya, dan dialog. Kreativitas bertanggung jawab mempertemukan keindahan dengan manfaat."],
      ],
      applications: ["Mencantumkan sumber karya", "Menghindari konten merendahkan", "Menggunakan seni untuk kampanye kebaikan"],
      questions: ["Mengapa karya indah belum tentu baik?", "Bagaimana hak cipta berkaitan dengan amanah?", "Apa peran seni dalam membangun harmoni?"],
      project: "Ciptakan poster, puisi, audio, atau karya visual bertema akhlak mulia disertai pernyataan etika karya.",
    },
    {
      id: "IX-9", grade: "IX", semester: "Genap", number: 9, allocation: 9,
      element: "Fikih",
      title: "Imam Mazhab dan Keteguhan Beribadah",
      overview: "Imam mazhab mengembangkan pemahaman fikih melalui keilmuan, metode, dan konteks. Mengenal mereka membantu murid menghargai perbedaan pendapat yang memiliki dasar serta tidak mudah menyalahkan.",
      objectives: ["Mengenal empat imam mazhab", "Menjelaskan sebab perbedaan fikih", "Menerapkan adab dalam perbedaan"],
      concepts: [
        ["Imam Abu Hanifah", "Dikenal memiliki perhatian terhadap penalaran hukum dan konteks persoalan. Ketelitian metode menunjukkan bahwa keputusan fikih tidak dibuat secara sembarangan."],
        ["Imam Malik", "Memberi perhatian pada hadits dan praktik penduduk Madinah. Lingkungan keilmuan dapat menjadi salah satu pertimbangan dalam memahami penerapan ajaran."],
        ["Imam Syafi'i dan Imam Ahmad", "Imam Syafi'i berkontribusi dalam sistematisasi usul fikih, sedangkan Imam Ahmad dikenal luas dalam hadits dan keteguhan. Keempat imam sama-sama memiliki kedalaman ilmu serta adab."],
        ["Adab ikhtilaf", "Perbedaan dapat muncul karena dalil yang diterima, pemahaman bahasa, metode, atau konteks. Murid mengikuti bimbingan yang dapat dipercaya tanpa mengejek praktik yang memiliki dasar."],
      ],
      applications: ["Tidak memperdebatkan masalah cabang dengan kasar", "Bertanya kepada guru ketika berbeda", "Membedakan perbedaan ilmiah dan klaim tanpa dasar"],
      questions: ["Mengapa ulama dapat berbeda pendapat?", "Apa syarat menghargai perbedaan fikih?", "Bagaimana bersikap ketika praktik teman berbeda?"],
      project: "Buat dialog adab perbedaan tentang satu masalah fikih tanpa menentukan pihak lain pasti salah.",
    },
    {
      id: "IX-10", grade: "IX", semester: "Genap", number: 10, allocation: 9,
      element: "Sejarah Peradaban Islam",
      title: "Mengapresiasi Peradaban Daulah Safawi dan Mughal",
      overview: "Daulah Safawi dan Mughal memberikan warisan pemerintahan, seni, arsitektur, ekonomi, dan kebudayaan. Kajian perbandingan membantu murid melihat persamaan, perbedaan, kontribusi, serta tantangannya secara proporsional.",
      objectives: ["Menjelaskan perkembangan Safawi dan Mughal", "Membandingkan warisan peradaban", "Mengambil ibrah dari kemajuan dan konflik"],
      concepts: [
        ["Daulah Safawi", "Safawi berkembang di Persia dengan warisan pemerintahan, perdagangan, kota, seni, karpet, kaligrafi, dan arsitektur yang kuat."],
        ["Daulah Mughal", "Mughal berkembang di India dan dikenal melalui tata kelola, ekonomi, karya sastra, seni taman, serta arsitektur monumental."],
        ["Pertemuan budaya", "Peradaban lahir dari interaksi masyarakat, pengetahuan, bahasa, dan tradisi. Pertemuan budaya dapat menghasilkan kreativitas ketika disertai penghormatan serta keadilan."],
        ["Ibrah sejarah", "Kepemimpinan, ilmu, ekonomi, toleransi, konflik, dan perebutan kekuasaan memengaruhi keberlanjutan. Warisan perlu diapresiasi tanpa menutupi persoalan."],
      ],
      applications: ["Membandingkan sumber sejarah", "Menghargai warisan budaya", "Memisahkan apresiasi karya dari pembenaran semua kebijakan"],
      questions: ["Apa perbedaan utama warisan Safawi dan Mughal?", "Bagaimana pertemuan budaya menghasilkan karya baru?", "Mengapa sejarah perlu dilihat secara proporsional?"],
      project: "Buat matriks perbandingan Safawi dan Mughal: wilayah, tokoh, tata kelola, ilmu, seni, tantangan, dan ibrah.",
    },
  ];

  const cp = {
    regulation: "Keputusan Kepala BKPDM Nomor 020 Tahun 2026",
    amendment: "Perubahan atas Keputusan Kepala BSKAP Nomor 046/H/KR/2025",
    sourceUrl: "https://bkpdm.kemendikdasmen.go.id/publikasi/capaian-pembelajaran-baru-telah-terbit-yang-berubah-hanya-mata-pelajaran-agama-dan-budi-pekerti",
    note: "Ringkasan operasional berikut membantu penyusunan perangkat sekolah. Untuk kutipan hukum dan rumusan resmi lengkap, gunakan dokumen keputusan pada sumber pemerintah.",
    phase: "Pada akhir Fase D, murid membangun kemampuan memahami, menghayati, dan menerapkan ajaran Islam secara utuh melalui lima elemen yang saling terhubung, dengan penekanan pada akhlak, penalaran, pengamalan, dan tanggung jawab dalam kehidupan nyata.",
    elements: [
      ["Al Qur'an dan Hadits", "Membaca, memahami, menganalisis pesan, dan mengamalkan nilai Al Qur'an serta Hadits pada tema keimanan, ilmu, lingkungan, toleransi, dan kehidupan sosial."],
      ["Akidah", "Memahami rukun iman dan hal-hal yang menguatkannya, kemudian menunjukkan dampaknya melalui sikap optimis, bertanggung jawab, dan berintegritas."],
      ["Akhlak", "Memahami dan membiasakan akhlak mulia dalam hubungan dengan Allah Subhanahu Wata'ala, diri, sesama, lingkungan, serta ruang digital."],
      ["Fikih", "Memahami dan mempraktikkan ketentuan ibadah serta muamalah secara benar, moderat, bertanggung jawab, dan sesuai konteks."],
      ["Sejarah Peradaban Islam", "Menganalisis perkembangan peradaban Islam, kontribusi tokoh, dinamika masyarakat, dan ibrah yang relevan bagi kehidupan masa kini."],
    ],
  };

  const academicCalendar = [
    ["13 Juli 2026", "Awal Tahun Ajaran 2026/2027 dan hari pertama masuk sekolah", "Terkonfirmasi melalui publikasi Dindikpora Banjarnegara"],
    ["13–17 Juli 2026", "MPLS ramah", "Sesuaikan kegiatan dengan ketentuan sekolah"],
    ["Juli–Desember 2026", "Rentang Semester Gasal", "Tanggal asesmen dan libur menunggu/menyesuaikan kalender resmi daerah"],
    ["Desember 2026", "Asesmen akhir Semester Gasal dan pembagian laporan hasil belajar", "Tanggal ditetapkan satuan pendidikan sesuai kalender resmi"],
    ["Januari–Juni 2027", "Rentang Semester Genap", "Sesuaikan hari pertama masuk dan libur dengan keputusan resmi"],
    ["Juni 2027", "Asesmen akhir Tahun Ajaran dan pembagian laporan hasil belajar", "Tanggal ditetapkan satuan pendidikan sesuai kalender resmi"],
  ];

  window.PAIBP_DATA = { chapters, cp, academicCalendar };
})();
