(() => {
  "use strict";

  /*
   * Bank Hadits Riwayat untuk pembaca luring.
   * Teks Arab yang ditampilkan adalah matan atau bagian matan yang langsung
   * berkaitan dengan tema bab. Tautan sumber dicantumkan untuk pemeriksaan.
   */
  const records = [
    {
      id: "sunnah-explains-quran",
      keywords: ["fungsi sunnah", "fungsi hadits", "berpegang pada petunjuk", "kedudukan sunnah"],
      title: "Kedudukan Sunnah bersama Al Qur'an",
      source: "Hadits Riwayat Abu Dawud no. 4604",
      arabic: "أَلَا إِنِّي أُوتِيتُ الْكِتَابَ وَمِثْلَهُ مَعَهُ",
      meaning: "Ketahuilah, sesungguhnya aku diberi Al Qur'an dan sesuatu yang semisal dengannya bersama Al Qur'an.",
      note: "Bagian matan ini menegaskan kedudukan Sunnah sebagai penjelas dan pedoman bersama Al Qur'an. Pemahaman hukum tetap memerlukan kajian hadits secara utuh dan bimbingan guru.",
      url: "https://sunnah.com/abudawud:4604",
    },
    {
      id: "earth-trust",
      keywords: ["penciptaan dan tanggung jawab terhadap alam", "tanggung jawab terhadap alam", "menjaga alam"],
      title: "Amanah manusia dalam kehidupan dunia",
      source: "Hadits Riwayat Muslim no. 2742",
      arabic: "إِنَّ الدُّنْيَا حُلْوَةٌ خَضِرَةٌ وَإِنَّ اللَّهَ مُسْتَخْلِفُكُمْ فِيهَا فَيَنْظُرُ كَيْفَ تَعْمَلُونَ",
      meaning: "Sesungguhnya dunia itu indah dan hijau. Allah Subhanahu Wata'ala menjadikan kalian silih berganti di dalamnya untuk melihat bagaimana kalian berbuat.",
      note: "Bagian matan yang ditampilkan berkaitan dengan amanah dan tanggung jawab manusia dalam memperlakukan kehidupan dunia.",
      url: "https://sunnah.com/muslim:2742",
    },
    {
      id: "guard-tongue",
      keywords: ["menjaga kehormatan dan lisan", "menjaga lisan", "berkata baik"],
      title: "Berkata baik atau diam",
      source: "Hadits Riwayat Al-Bukhari no. 6475",
      arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
      meaning: "Siapa yang beriman kepada Allah Subhanahu Wata'ala dan Hari Akhir hendaklah berkata baik atau diam.",
      note: "Hadits ini menjadi dasar menjaga lisan, kehormatan, dan etika komunikasi, termasuk di ruang digital.",
      url: "https://sunnah.com/bukhari:6475",
    },
    {
      id: "justice",
      keywords: ["sikap adil", "adil, seimbang", "kezaliman", "keadilan"],
      title: "Larangan berbuat zalim",
      source: "Hadits Riwayat Muslim no. 2578",
      arabic: "اتَّقُوا الظُّلْمَ فَإِنَّ الظُّلْمَ ظُلُمَاتٌ يَوْمَ الْقِيَامَةِ",
      meaning: "Jauhilah kezaliman, karena kezaliman menjadi kegelapan pada Hari Kiamat.",
      note: "Sikap adil dimulai dengan menghindari tindakan yang merampas hak atau merugikan orang lain.",
      url: "https://sunnah.com/muslim:2578",
    },
    {
      id: "seek-knowledge",
      keywords: ["keutamaan menuntut ilmu", "menuntut ilmu", "jalan ilmu"],
      title: "Jalan menuju ilmu",
      source: "Hadits Riwayat Muslim no. 2699a",
      arabic: "وَمَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ",
      meaning: "Siapa yang menempuh jalan untuk mencari ilmu, Allah Subhanahu Wata'ala memudahkan baginya jalan menuju surga.",
      note: "Menuntut ilmu mencakup kesungguhan, adab, pemeriksaan sumber, dan pengamalan pengetahuan.",
      url: "https://sunnah.com/muslim:2699a",
    },
    {
      id: "young-and-elders",
      keywords: ["menyayangi yang muda", "menghormati yang tua", "muda dan menghormati"],
      title: "Menyayangi yang muda dan menghormati yang tua",
      source: "Hadits Riwayat At-Tirmidzi no. 1920",
      arabic: "لَيْسَ مِنَّا مَنْ لَمْ يَرْحَمْ صَغِيرَنَا وَيَعْرِفْ شَرَفَ كَبِيرِنَا",
      meaning: "Bukan termasuk golongan kami orang yang tidak menyayangi yang muda dan tidak mengetahui kehormatan orang yang lebih tua.",
      note: "Hadits ini menguatkan adab lintas generasi di keluarga, sekolah, dan masyarakat.",
      url: "https://sunnah.com/tirmidhi:1920",
    },
    {
      id: "mercy",
      keywords: ["kasih sayang", "berbelas kasih", "rahmat"],
      title: "Kasih sayang kepada makhluk",
      source: "Hadits Riwayat Abu Dawud no. 4941",
      arabic: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ ارْحَمُوا أَهْلَ الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ",
      meaning: "Orang-orang yang penyayang akan disayangi oleh Ar-Rahman. Sayangilah yang ada di bumi, niscaya kalian disayangi oleh Yang di langit.",
      note: "Kasih sayang ditunjukkan melalui perlindungan, bantuan, ucapan baik, dan tindakan yang tidak menyakiti.",
      url: "https://sunnah.com/abudawud:4941",
    },
    {
      id: "qadar-and-effort",
      keywords: ["ketetapan Allah dan ikhtiar", "ikhtiar", "takdir", "ketetapan Allah"],
      title: "Ikhtiar, pertolongan Allah, dan takdir",
      source: "Hadits Riwayat Muslim no. 2664",
      arabic: "احْرِصْ عَلَى مَا يَنْفَعُكَ وَاسْتَعِنْ بِاللَّهِ وَلَا تَعْجِزْ",
      meaning: "Bersungguh-sungguhlah pada hal yang bermanfaat bagimu, mohonlah pertolongan kepada Allah Subhanahu Wata'ala, dan jangan lemah.",
      note: "Iman kepada takdir tidak menghapus ikhtiar. Murid tetap berusaha secara benar lalu menerima hasil dengan tawakal.",
      url: "https://sunnah.com/muslim:2664",
    },
    {
      id: "ninety-nine-names",
      keywords: ["sembilan puluh sembilan nama", "99 nama", "nama Allah"],
      title: "Sembilan puluh sembilan nama Allah",
      source: "Hadits Riwayat Al-Bukhari no. 2736",
      arabic: "إِنَّ لِلَّهِ تِسْعَةً وَتِسْعِينَ اسْمًا مِائَةً إِلَّا وَاحِدًا مَنْ أَحْصَاهَا دَخَلَ الْجَنَّةَ",
      meaning: "Sesungguhnya Allah Subhanahu Wata'ala memiliki sembilan puluh sembilan nama, seratus kurang satu. Siapa yang menjaganya akan masuk surga.",
      note: "Mempelajari Asmaul Husna mencakup mengenal, memahami, mengingat, dan mengamalkan nilai yang benar sesuai kandungannya.",
      url: "https://sunnah.com/bukhari:2736",
    },
    {
      id: "sujud-sahwi",
      keywords: ["sujud syukur, sahwi, dan tilawah", "sujud sahwi", "kelupaan dalam sholat"],
      title: "Sujud sahwi ketika lupa dalam sholat",
      source: "Hadits Riwayat Al-Bukhari no. 1230",
      arabic: "فَلَمَّا أَتَمَّ صَلَاتَهُ سَجَدَ سَجْدَتَيْنِ فَكَبَّرَ فِي كُلِّ سَجْدَةٍ",
      meaning: "Ketika Nabi Muhammad Sholallohu 'Alaihi Wasallam menyempurnakan sholatnya, beliau bersujud dua kali dan bertakbir pada setiap sujud.",
      note: "Bagian matan ini berkaitan khusus dengan sujud sahwi. Sujud syukur dan sujud tilawah memiliki dalil serta ketentuan yang dipelajari pada bagian tersendiri.",
      url: "https://sunnah.com/bukhari:1230",
    },
    {
      id: "accountability",
      keywords: ["muhasabah dan tanggung jawab amal", "tanggung jawab amal", "setiap kalian adalah pemimpin"],
      title: "Setiap orang memikul tanggung jawab",
      source: "Hadits Riwayat Al-Bukhari no. 893",
      arabic: "كُلُّكُمْ رَاعٍ وَكُلُّكُمْ مَسْئُولٌ عَنْ رَعِيَّتِهِ",
      meaning: "Setiap kalian adalah pemimpin dan setiap kalian akan dimintai pertanggungjawaban atas yang berada dalam tanggungannya.",
      note: "Muhasabah membantu seseorang menilai amanah, memperbaiki kesalahan, dan menyiapkan tindakan berikutnya.",
      url: "https://sunnah.com/bukhari:893",
    },
    {
      id: "travel-concession",
      keywords: ["mengambil keringanan syariat", "keringanan syariat", "rukhsah"],
      title: "Keringanan ketika perjalanan membawa kesulitan",
      source: "Hadits Riwayat Muslim no. 1115a",
      arabic: "لَيْسَ مِنَ الْبِرِّ أَنْ تَصُومُوا فِي السَّفَرِ",
      meaning: "Bukanlah kebajikan apabila kalian tetap berpuasa dalam perjalanan pada keadaan yang menimbulkan kesulitan seperti dalam peristiwa hadits ini.",
      note: "Hadits ini dibaca bersama konteksnya: musafir tersebut mengalami kesulitan. Rukhsah dipakai sesuai sebab dan ketentuan fikih.",
      url: "https://sunnah.com/muslim:1115a",
    },
    {
      id: "truthfulness",
      keywords: ["kejujuran yang menuntun", "kejujuran", "jujur"],
      title: "Kejujuran menuntun kepada kebaikan",
      source: "Hadits Riwayat Al-Bukhari no. 6094",
      arabic: "إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ",
      meaning: "Sesungguhnya kejujuran menuntun kepada kebajikan, dan kebajikan menuntun menuju surga.",
      note: "Kejujuran dilatih dalam ucapan, tugas, transaksi, penggunaan sumber, dan penyampaian informasi.",
      url: "https://sunnah.com/bukhari:6094",
    },
    {
      id: "eclipse-prayer",
      keywords: ["sholat gerhana", "gerhana, istisqa, dan jenazah", "gerhana"],
      title: "Tuntunan ketika terjadi gerhana",
      source: "Hadits Riwayat Al-Bukhari no. 1044",
      arabic: "فَإِذَا رَأَيْتُمْ ذَلِكَ فَادْعُوا اللَّهَ وَكَبِّرُوا وَصَلُّوا وَتَصَدَّقُوا",
      meaning: "Apabila kalian melihat gerhana, berdoalah kepada Allah Subhanahu Wata'ala, bertakbirlah, laksanakan sholat, dan bersedekahlah.",
      note: "Bagian matan ini berkaitan khusus dengan sholat gerhana. Sholat istisqa dan jenazah memiliki dalil serta tata cara tersendiri.",
      url: "https://sunnah.com/bukhari:1044",
    },
    {
      id: "one-prophetic-message",
      keywords: ["kesatuan risalah para nabi", "kesatuan risalah", "para nabi"],
      title: "Kesatuan pokok agama para nabi",
      source: "Hadits Riwayat Al-Bukhari no. 3443",
      arabic: "وَالْأَنْبِيَاءُ إِخْوَةٌ لِعَلَّاتٍ أُمَّهَاتُهُمْ شَتَّى وَدِينُهُمْ وَاحِدٌ",
      meaning: "Para nabi adalah saudara sebapak; ibu mereka berbeda, sedangkan agama mereka satu.",
      note: "Para nabi 'Alaihissalam membawa pokok tauhid yang sama, sementara syariat rinci dapat berbeda sesuai ketetapan Allah Subhanahu Wata'ala.",
      url: "https://sunnah.com/bukhari:3443",
    },
    {
      id: "beauty-without-pride",
      keywords: ["keindahan dan akhlak", "keindahan", "akhlak yang baik"],
      title: "Keindahan tidak sama dengan kesombongan",
      source: "Hadits Riwayat Muslim no. 91a",
      arabic: "إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ الْكِبْرُ بَطَرُ الْحَقِّ وَغَمْطُ النَّاسِ",
      meaning: "Sesungguhnya Allah Subhanahu Wata'ala Mahaindah dan mencintai keindahan. Kesombongan adalah menolak kebenaran dan merendahkan manusia.",
      note: "Kerapian dan keindahan dijaga tanpa berlebihan, menolak kebenaran, atau merendahkan orang lain.",
      url: "https://sunnah.com/muslim:91a",
    },
    {
      id: "aqiqah",
      keywords: ["akikah dan kurban", "akikah", "aqiqah"],
      title: "Tuntunan akikah",
      source: "Hadits Riwayat At-Tirmidzi no. 1522",
      arabic: "الْغُلَامُ مُرْتَهَنٌ بِعَقِيقَتِهِ يُذْبَحُ عَنْهُ يَوْمَ السَّابِعِ وَيُسَمَّى وَيُحْلَقُ رَأْسُهُ",
      meaning: "Seorang anak berkaitan dengan akikahnya; disembelihkan untuknya pada hari ketujuh, diberi nama, dan dicukur kepalanya.",
      note: "Hadits ini berkaitan dengan akikah. Kurban memiliki dalil, waktu, syarat, dan pembagian daging yang dipelajari secara tersendiri.",
      url: "https://sunnah.com/tirmidhi:1522",
    },
  ];

  window.PAIBP_HADITH = { records };
})();
