(() => {
  const dua = [
    {
      id: "morning-kingdom",
      categories: ["pagi"],
      title: "Memasuki waktu pagi",
      arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
      meaning: "Kami memasuki pagi dan seluruh kerajaan milik Allah. Segala puji bagi Allah; tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya.",
      repetition: "1 kali",
      source: "Hadits Riwayat Muslim no. 2723",
    },
    {
      id: "evening-kingdom",
      categories: ["petang"],
      title: "Memasuki waktu petang",
      arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
      meaning: "Kami memasuki petang dan seluruh kerajaan milik Allah. Segala puji bagi Allah; tidak ada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya.",
      repetition: "1 kali",
      source: "Hadits Riwayat Muslim no. 2723",
    },
    {
      id: "morning-by-you",
      categories: ["pagi"],
      title: "Dengan pertolongan Allah memasuki pagi",
      arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
      meaning: "Ya Allah, dengan pertolongan-Mu kami memasuki pagi dan petang, dengan-Mu kami hidup dan mati, dan kepada-Mu kebangkitan.",
      repetition: "1 kali",
      source: "Hadits Riwayat Abu Dawud no. 5068; At-Tirmidzi no. 3391",
    },
    {
      id: "evening-by-you",
      categories: ["petang"],
      title: "Dengan pertolongan Allah memasuki petang",
      arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ",
      meaning: "Ya Allah, dengan pertolongan-Mu kami memasuki petang dan pagi, dengan-Mu kami hidup dan mati, dan kepada-Mu tempat kembali.",
      repetition: "1 kali",
      source: "Hadits Riwayat Abu Dawud no. 5068; At-Tirmidzi no. 3391",
    },
    {
      id: "sayyidul-istighfar",
      categories: ["pagi", "petang", "hisnul"],
      title: "Sayyidul istighfar",
      arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
      meaning: "Ya Allah, Engkau Tuhanku, tidak ada sesembahan yang berhak disembah selain Engkau. Aku mengakui nikmat-Mu dan dosaku; ampunilah aku, karena hanya Engkau yang mengampuni dosa.",
      repetition: "1 kali pagi dan petang",
      source: "Hadits Riwayat Al-Bukhari no. 6306",
    },
    {
      id: "wellbeing",
      categories: ["pagi", "petang", "hisnul"],
      title: "Memohon ampunan dan keselamatan",
      arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
      meaning: "Ya Allah, aku memohon kepada-Mu ampunan dan keselamatan di dunia dan akhirat.",
      repetition: "1 kali",
      source: "Hadits Riwayat Abu Dawud no. 5074; Ibnu Majah no. 3871",
    },
    {
      id: "no-harm",
      categories: ["pagi", "petang"],
      title: "Memohon perlindungan dari bahaya",
      arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
      meaning: "Dengan nama Allah, yang bersama nama-Nya tidak ada sesuatu pun di bumi dan langit yang dapat membahayakan; Dia Maha Mendengar lagi Maha Mengetahui.",
      repetition: "3 kali pagi dan petang",
      source: "Hadits Riwayat Abu Dawud no. 5088; At-Tirmidzi no. 3388",
    },
    {
      id: "contentment",
      categories: ["pagi", "petang"],
      title: "Ridha kepada Allah, Islam, dan Nabi",
      arabic: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ نَبِيًّا",
      meaning: "Aku ridha Allah sebagai Tuhan, Islam sebagai agama, dan Muhammad sebagai nabi.",
      repetition: "3 kali pagi dan petang",
      source: "Hadits Riwayat Abu Dawud no. 5072; At-Tirmidzi no. 3389",
    },
    {
      id: "glorify",
      categories: ["pagi", "petang"],
      title: "Tasbih dan tahmid",
      arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
      meaning: "Maha Suci Allah dan segala puji bagi-Nya.",
      repetition: "100 kali",
      source: "Hadits Riwayat Muslim no. 2692",
    },
    {
      id: "before-sleep",
      categories: ["hisnul"],
      title: "Doa sebelum tidur",
      arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
      meaning: "Dengan nama-Mu, ya Allah, aku mati dan aku hidup.",
      repetition: "1 kali",
      source: "Hadits Riwayat Al-Bukhari no. 6324",
    },
    {
      id: "wake-up",
      categories: ["hisnul"],
      title: "Doa bangun tidur",
      arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
      meaning: "Segala puji bagi Allah yang menghidupkan kami setelah mematikan kami; kepada-Nya kebangkitan.",
      repetition: "1 kali",
      source: "Hadits Riwayat Al-Bukhari no. 6324",
    },
    {
      id: "leave-home",
      categories: ["hisnul"],
      title: "Doa keluar rumah",
      arabic: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
      meaning: "Dengan nama Allah, aku bertawakal kepada Allah; tidak ada daya dan kekuatan selain dengan pertolongan Allah.",
      repetition: "1 kali",
      source: "Hadits Riwayat Abu Dawud no. 5095; At-Tirmidzi no. 3426",
    },
    {
      id: "enter-mosque",
      categories: ["hisnul"],
      title: "Doa masuk masjid",
      arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
      meaning: "Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.",
      repetition: "1 kali",
      source: "Hadits Riwayat Muslim no. 713",
    },
    {
      id: "leave-mosque",
      categories: ["hisnul"],
      title: "Doa keluar masjid",
      arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
      meaning: "Ya Allah, sesungguhnya aku memohon karunia-Mu.",
      repetition: "1 kali",
      source: "Hadits Riwayat Muslim no. 713",
    },
    {
      id: "before-eating",
      categories: ["hisnul"],
      title: "Sebelum makan",
      arabic: "بِسْمِ اللَّهِ",
      meaning: "Dengan nama Allah.",
      repetition: "1 kali",
      source: "Hadits Riwayat Al-Bukhari no. 5376; Muslim no. 2022",
    },
    {
      id: "anxiety",
      categories: ["hisnul"],
      title: "Doa ketika mengalami kesusahan",
      arabic: "لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ",
      meaning: "Tidak ada sesembahan yang berhak disembah selain Allah Yang Mahaagung lagi Maha Penyantun; Tuhan pemilik Arasy yang agung.",
      repetition: "Dibaca ketika mengalami kesusahan",
      source: "Hadits Riwayat Al-Bukhari no. 6346; Muslim no. 2730",
    },
  ];

  const fastingRules = [
    ["Ramadhan", "Wajib bagi Muslim yang memenuhi syarat; rukhsah dan qadha berlaku menurut ketentuan fikih."],
    ["Senin dan Kamis", "Sunnah mingguan, selama tidak bertepatan dengan hari yang dilarang berpuasa."],
    ["Ayyamul Bidh", "Sunnah pada tanggal 13, 14, dan 15 setiap bulan Hijriah; tanggal 13 Dzulhijjah termasuk hari tasyrik sehingga tidak ditandai sebagai puasa."],
    ["Enam hari Syawal", "Sunnah enam hari selama bulan Syawal setelah Idul Fitri; boleh berurutan atau terpisah."],
    ["Tasu'a dan Asyura", "Sunnah tanggal 9 dan 10 Muharram. Praktik juga dapat dilengkapi tanggal 11 menurut penjelasan fikih yang diikuti."],
    ["Arafah", "Sunnah tanggal 9 Dzulhijjah bagi yang tidak sedang berhaji."],
    ["Awal Dzulhijjah", "Amal sholeh dianjurkan pada sembilan hari pertama; puasa termasuk amal yang dapat dikerjakan sesuai kemampuan."],
    ["Puasa pada bulan Muharram", "Memperbanyak puasa sunnah pada bulan Muharram dianjurkan; tanggal 9–10 memiliki tuntunan khusus Tasu'a dan Asyura."],
    ["Memperbanyak puasa pada bulan Sya'ban", "Nabi Muhammad Sholallohu 'Alaihi Wasallam diriwayatkan banyak berpuasa pada bulan Sya'ban. Pelaksanaannya perlu memperhatikan kemampuan dan ketentuan menjelang Ramadhan."],
    ["Tiga hari setiap bulan", "Sunnah berpuasa tiga hari setiap bulan. Tanggal 13–15 (Ayyamul Bidh) merupakan pilihan yang utama, dengan pengecualian hari yang dilarang."],
    ["Puasa Nabi Dawud", "Sunnah berselang-seling sehari berpuasa dan sehari tidak, bagi yang mampu dan tidak mengabaikan kewajiban."],
    ["Qadha, nazar, dan kafarat", "Puasa wajib karena sebab tertentu. Ketentuannya perlu dipelajari sesuai kasus dan bimbingan guru/ulama yang kompeten."],
    ["Puasa pengganti dam dalam haji", "Wajib secara bersyarat pada keadaan haji tertentu bagi orang yang tidak memperoleh hadyu. Rinciannya dipelajari pada fikih haji bersama pembimbing yang kompeten."],
    ["Hari yang dilarang", "Tidak berpuasa pada Idul Fitri, Idul Adha, dan hari tasyrik 11–13 Dzulhijjah, kecuali pengecualian fikih yang sangat khusus."],
  ];

  const historicDates = [
    { month: 1, day: 10, label: "Asyura", note: "Hari yang dimuliakan; puasa Asyura memiliki tuntunan sahih." },
    { month: 3, day: 12, label: "Maulid Nabi", note: "Tanggal peringatan yang dikenal luas; rincian tanggal kelahiran diperselisihkan sejarawan." },
    { month: 7, day: 27, label: "Isra dan Mi'raj", note: "Tanggal peringatan yang populer; penetapan tanggal tepatnya diperselisihkan." },
    { month: 9, day: 17, label: "Perang Badar", note: "Dikenang luas terjadi pada Ramadhan tahun 2 H." },
    { month: 9, day: 17, label: "Nuzulul Qur'an", note: "Tanggal peringatan yang umum di Indonesia; proses turunnya Al Qur'an memiliki pembahasan riwayat dan tahapan." },
    { month: 9, day: 20, label: "Fathu Makkah", note: "Dikenang luas terjadi pada Ramadhan tahun 8 H; riwayat tanggal dapat berbeda." },
    { month: 10, day: 1, label: "Idul Fitri", note: "Hari raya setelah menyempurnakan puasa Ramadhan." },
    { month: 10, day: 7, label: "Perang Uhud", note: "Sering disebut terjadi pada 7 Syawal 3 H; sumber sejarah juga memuat perbedaan tanggal." },
    { month: 12, day: 9, label: "Hari Arafah", note: "Puncak wukuf bagi jamaah haji; puasa sunnah bagi yang tidak berhaji." },
    { month: 12, day: 10, label: "Idul Adha", note: "Hari raya kurban; dilanjutkan hari tasyrik 11–13 Dzulhijjah." },
  ];

  const dailyInsights = [
    {
      type: "Al Qur'an",
      text: "Allah Subhanahu Wata'ala meninggikan orang-orang beriman dan berilmu beberapa derajat.",
      source: "Al Qur'an Surat Al-Mujadilah ayat 11",
      detail: "Tema: adab majelis dan kemuliaan ilmu.",
    },
    {
      type: "Hadits",
      text: "Nilai suatu amal berkaitan dengan niat yang melandasinya.",
      source: "Hadits Riwayat Al-Bukhari no. 1; Muslim no. 1907",
      detail: "Bab permulaan wahyu/niat; nomor mengikuti penomoran basis data hadits.",
    },
    {
      type: "Hadits",
      text: "Seorang Muslim yang baik menjaga orang lain dari gangguan lisan dan tangannya.",
      source: "Hadits Riwayat Al-Bukhari no. 10; Muslim no. 40",
      detail: "Tema: menjaga lisan, tindakan, dan keamanan sesama.",
    },
    {
      type: "Kitab",
      text: "Menjaga lisan adalah latihan akhlak harian: berbicara ketika ada maslahat dan menahan diri ketika ucapan membawa mudarat.",
      source: "Imam An-Nawawi, Al-Adzkar, Bab Menjaga Lisan",
      detail: "Intisari editorial; halaman berbeda menurut edisi sehingga tidak dicantumkan tanpa verifikasi edisi.",
    },
    {
      type: "Al Qur'an",
      text: "Berita dari sumber yang meragukan harus diperiksa agar keputusan tidak mencelakakan orang lain.",
      source: "Al Qur'an Surat Al-Hujurat ayat 6",
      detail: "Tema: tabayun dan tanggung jawab informasi.",
    },
    {
      type: "Hadits",
      text: "Allah Subhanahu Wata'ala mencintai kelembutan dalam berbagai urusan.",
      source: "Hadits Riwayat Al-Bukhari no. 6024; Muslim no. 2165",
      detail: "Tema: rifq atau kelembutan.",
    },
    {
      type: "Kitab",
      text: "Belajar yang bermanfaat memerlukan niat yang lurus, kesungguhan, adab kepada guru, dan pengamalan.",
      source: "Az-Zarnuji, Ta'lim al-Muta'allim, bagian niat dan adab belajar",
      detail: "Intisari editorial; halaman bergantung pada edisi cetak.",
    },
    {
      type: "Fatwa Ulama",
      text: "Menjaga lingkungan menuntut pengelolaan sampah yang baik, pencegahan kerusakan, pendidikan masyarakat, dan ikhtiar ekonomi yang tetap menjaga keseimbangan ekosistem.",
      source: "Komisi Fatwa MUI, Fatwa No. 41 Tahun 2014",
      detail: "Intisari bagian rekomendasi, halaman 9 pada berkas PDF MUI.",
      url: "https://mirror.mui.or.id/wp-content/uploads/files/fatwa/Pengelolaan-Sampah-utk-Mencegah-Kerusakan-Lingkungan.pdf",
    },
    {
      type: "Fatwa Ulama Dunia",
      text: "Fatwa harus lahir dari keahlian, pemahaman dalil, serta pembacaan keadaan; pertanyaan hukum tidak selayaknya dijawab sekedar berdasarkan dugaan.",
      source: "Dar al-Ifta Mesir, The Craft of Issuing Fatwas",
      detail: "Intisari editorial dari artikel resmi lembaga fatwa Mesir.",
      url: "https://www.dar-alifta.org/en/article/details/77/the-craft-of-issuing-fatwas",
    },
    {
      type: "Nasihat Ulama Dunia",
      text: "Akhlak melindungi keyakinan, harta, kehormatan, ketenteraman, dan kehidupan bersama; ia bukan hiasan tambahan dalam beragama.",
      source: "Dar al-Ifta Mesir, Akhlaq: Ethical Theory in Islam",
      detail: "Intisari editorial dari artikel resmi Dar al-Ifta.",
      url: "https://www.dar-alifta.org/en/article/details/66/akhlaq-ethical-theory-in-islam",
    },
    {
      type: "Nasihat Ustadz",
      text: "Perbaikan diri perlu seimbang: jangan merasa cukup karena unggul pada satu sisi ibadah sementara mengabaikan kekurangan akhlak dan tanggung jawab lain.",
      source: "Dr. Omar Suleiman, Becoming the Best Version of Yourself",
      detail: "Intisari editorial dari kajian Yaqeen Institute.",
      url: "https://yaqeeninstitute.org/watch/series/lecture/becoming-the-best-version-of-yourself",
    },
    {
      type: "Nasihat Ustadzah/Peneliti",
      text: "Sejarah keilmuan Islam juga dibangun oleh ulama perempuan yang berperan penting dalam meriwayatkan, mengajar, meneliti, dan menjaga kesinambungan ilmu.",
      source: "Jude Elziq, Female Scholars in Islamic History",
      detail: "Intisari editorial; Yaqeen Institute, artikel 30 April 2026.",
      url: "https://yaqeeninstitute.org/read/paper/female-scholars-in-islamic-history-revisiting-their-pivotal-role",
    },
    {
      type: "Al Qur'an",
      text: "Kerusakan di darat dan laut berkaitan dengan perbuatan manusia sehingga manusia perlu kembali memperbaiki diri.",
      source: "Al Qur'an Surat Ar-Rum ayat 41",
      detail: "Tema: tanggung jawab lingkungan.",
    },
    {
      type: "Hadits",
      text: "Siapa yang beriman kepada Allah Subhanahu Wata'ala dan Hari Akhir hendaknya berkata baik atau diam.",
      source: "Hadits Riwayat Al-Bukhari no. 6018; Muslim no. 47",
      detail: "Tema: etika komunikasi.",
    },
    {
      type: "Al Qur'an",
      text: "Manusia diperintah saling mengenal; kemuliaan tidak ditentukan oleh suku, tetapi ketakwaan.",
      source: "Al Qur'an Surat Al-Hujurat ayat 13",
      detail: "Tema: martabat manusia dan hidup bersama.",
    },
  ];

  const quranInsightBank = [
    ["Al Qur'an Surat Al-Fatihah ayat 5–6", "Ibadah hanya ditujukan kepada Allah Subhanahu Wata'ala dan pertolongan dimohon kepada-Nya sambil terus meminta petunjuk jalan yang lurus.", "Tema: tauhid, doa, dan kebutuhan kepada petunjuk."],
    ["Al Qur'an Surat Al-Baqarah ayat 21", "Manusia diajak menyembah Allah Subhanahu Wata'ala yang menciptakan mereka agar tumbuh ketakwaan.", "Tema: tujuan ibadah dan ketakwaan."],
    ["Al Qur'an Surat Al-Baqarah ayat 45", "Kesabaran dan sholat menjadi sarana meminta pertolongan ketika menghadapi kesulitan.", "Tema: daya tahan, ibadah, dan pertolongan."],
    ["Al Qur'an Surat Al-Baqarah ayat 152", "Mengingat Allah Subhanahu Wata'ala dan mensyukuri nikmat perlu dijaga tanpa mengingkari karunia-Nya.", "Tema: dzikir dan syukur."],
    ["Al Qur'an Surat Al-Baqarah ayat 177", "Kebajikan menghubungkan iman dengan kepedulian sosial, sholat, zakat, menepati janji, dan kesabaran.", "Tema: iman yang tampak dalam amal."],
    ["Al Qur'an Surat Al-Baqarah ayat 195", "Manusia tidak boleh menjatuhkan diri dalam kebinasaan dan diperintah berbuat ihsan.", "Tema: menjaga diri dan kualitas kebaikan."],
    ["Al Qur'an Surat Al-Baqarah ayat 256", "Tidak ada paksaan dalam agama; kebenaran dan kesesatan telah memiliki penjelasan.", "Tema: kebebasan bertanggung jawab dan keyakinan."],
    ["Al Qur'an Surat Al-Baqarah ayat 286", "Allah Subhanahu Wata'ala tidak membebani seseorang melampaui kesanggupannya.", "Tema: tanggung jawab, harapan, dan doa."],
    ["Al Qur'an Surat Ali 'Imran ayat 103", "Persatuan dijaga dengan berpegang pada petunjuk Allah Subhanahu Wata'ala dan tidak bercerai-berai.", "Tema: ukhuwah dan persatuan."],
    ["Al Qur'an Surat Ali 'Imran ayat 104", "Masyarakat yang baik menghadirkan ajakan kepada kebaikan dan upaya mencegah kemungkaran dengan ilmu dan adab.", "Tema: tanggung jawab sosial."],
    ["Al Qur'an Surat Ali 'Imran ayat 134", "Orang bertakwa berinfak, menahan amarah, dan memaafkan kesalahan orang lain.", "Tema: pengendalian diri dan pemaafan."],
    ["Al Qur'an Surat Ali 'Imran ayat 190–191", "Pergantian malam dan siang serta penciptaan langit dan bumi menjadi bahan dzikir dan berpikir.", "Tema: literasi alam dan kesadaran kepada Allah Subhanahu Wata'ala."],
    ["Al Qur'an Surat An-Nisa' ayat 36", "Tauhid disertai kewajiban berbuat baik kepada orang tua, kerabat, tetangga, dan pihak yang membutuhkan.", "Tema: ibadah dan kepedulian sosial."],
    ["Al Qur'an Surat An-Nisa' ayat 135", "Keadilan harus ditegakkan meskipun kesaksian itu berkaitan dengan diri sendiri atau orang terdekat.", "Tema: integritas dan keberanian moral."],
    ["Al Qur'an Surat Al-Ma'idah ayat 2", "Kerja sama diarahkan pada kebajikan dan takwa, bukan dosa dan permusuhan.", "Tema: kolaborasi yang bertanggung jawab."],
    ["Al Qur'an Surat Al-Ma'idah ayat 8", "Kebencian kepada suatu kelompok tidak boleh mendorong ketidakadilan.", "Tema: keadilan dalam perbedaan."],
    ["Al Qur'an Surat Al-Ma'idah ayat 32", "Menjaga kehidupan manusia memiliki nilai kemanusiaan yang sangat besar.", "Tema: perlindungan jiwa dan kemanusiaan."],
    ["Al Qur'an Surat Al-Ma'idah ayat 48", "Perbedaan menjadi ruang untuk berlomba dalam kebaikan, bukan alasan saling merendahkan.", "Tema: kompetisi dalam kebajikan."],
    ["Al Qur'an Surat Al-A'raf ayat 31", "Makan dan minum dibolehkan, tetapi perilaku berlebih-lebihan harus dihindari.", "Tema: keseimbangan dan konsumsi bertanggung jawab."],
    ["Al Qur'an Surat Al-Anfal ayat 27", "Amanah kepada Allah Subhanahu Wata'ala dan sesama tidak boleh dikhianati dengan sadar.", "Tema: menjaga kepercayaan."],
    ["Al Qur'an Surat Al-Anfal ayat 46", "Perselisihan yang tidak dikelola dapat melemahkan kekuatan; ketaatan dan kesabaran perlu dijaga.", "Tema: disiplin dan penyelesaian konflik."],
    ["Al Qur'an Surat At-Taubah ayat 105", "Manusia diperintah bekerja; amal akan terlihat dan dipertanggungjawabkan.", "Tema: etos kerja dan akuntabilitas."],
    ["Al Qur'an Surat Yunus ayat 57", "Petunjuk Allah Subhanahu Wata'ala menjadi nasihat dan penyembuh bagi penyakit hati.", "Tema: pendidikan hati dan petunjuk."],
    ["Al Qur'an Surat An-Nahl ayat 90", "Keadilan, ihsan, dan kepedulian diperintahkan; perbuatan keji, mungkar, dan permusuhan dilarang.", "Tema: prinsip akhlak sosial."],
    ["Al Qur'an Surat An-Nahl ayat 125", "Ajakan kepada jalan Allah Subhanahu Wata'ala dilakukan dengan hikmah, pelajaran yang baik, dan dialog terbaik.", "Tema: komunikasi dakwah yang bijak."],
    ["Al Qur'an Surat Al-Isra' ayat 23–24", "Berbakti kepada orang tua ditunjukkan melalui ucapan mulia, kerendahan hati, dan doa.", "Tema: adab kepada orang tua."],
    ["Al Qur'an Surat Al-Isra' ayat 26–27", "Hak kerabat dan orang yang membutuhkan perlu ditunaikan, sedangkan pemborosan harus dihindari.", "Tema: berbagi dan pengelolaan harta."],
    ["Al Qur'an Surat Al-Isra' ayat 36", "Seseorang tidak seharusnya mengikuti atau menyampaikan sesuatu yang tidak memiliki pengetahuan tentangnya.", "Tema: literasi informasi dan tanggung jawab."],
    ["Al Qur'an Surat Al-Isra' ayat 70", "Anak cucu Adam dimuliakan dan memperoleh berbagai sarana kehidupan.", "Tema: martabat manusia."],
    ["Al Qur'an Surat Taha ayat 114", "Doa untuk penambahan ilmu menunjukkan bahwa belajar merupakan perjalanan yang terus bertumbuh.", "Tema: kerendahan hati dalam belajar."],
    ["Al Qur'an Surat Al-Anbiya' ayat 107", "Nabi Muhammad Sholallohu 'Alaihi Wasallam diutus sebagai rahmat bagi seluruh alam.", "Tema: misi rahmat dan keteladanan."],
    ["Al Qur'an Surat Al-Hajj ayat 46", "Perjalanan dan pengamatan seharusnya menghidupkan hati untuk memahami, bukan hanya mengandalkan penglihatan.", "Tema: belajar melalui pengalaman dan refleksi."],
    ["Al Qur'an Surat Al-Mu'minun ayat 1–2", "Keberuntungan orang beriman terkait dengan kekhusyukan dalam sholat.", "Tema: kualitas ibadah dan kehadiran hati."],
    ["Al Qur'an Surat An-Nur ayat 30–31", "Menjaga pandangan dan kehormatan merupakan bagian dari kesucian diri.", "Tema: batas pergaulan dan kendali diri."],
    ["Al Qur'an Surat Al-Furqan ayat 63", "Hamba Allah Subhanahu Wata'ala berjalan rendah hati dan menanggapi ucapan jahil dengan damai.", "Tema: kerendahan hati dan kedamaian."],
    ["Al Qur'an Surat Al-'Ankabut ayat 69", "Orang yang bersungguh-sungguh di jalan kebaikan memperoleh bimbingan menuju jalan-jalan petunjuk.", "Tema: kesungguhan dan pertolongan."],
    ["Al Qur'an Surat Luqman ayat 17", "Sholat, ajakan kepada kebaikan, pencegahan kemungkaran, dan kesabaran membentuk tanggung jawab seorang mukmin.", "Tema: nasihat pendidikan Luqman."],
    ["Al Qur'an Surat Luqman ayat 18–19", "Kesombongan dalam pergaulan dihindari; cara berjalan dan suara dijaga dengan wajar.", "Tema: adab sosial dan komunikasi."],
    ["Al Qur'an Surat Al-Ahzab ayat 70–71", "Ucapan yang benar menjadi bagian dari takwa dan jalan perbaikan amal.", "Tema: kejujuran komunikasi."],
    ["Al Qur'an Surat Az-Zumar ayat 9", "Orang yang mengetahui dan yang tidak mengetahui tidaklah sama; hanya orang berakal yang mengambil pelajaran.", "Tema: kedudukan ilmu."],
    ["Al Qur'an Surat Az-Zumar ayat 53", "Orang yang melampaui batas terhadap dirinya tidak boleh berputus asa dari rahmat Allah Subhanahu Wata'ala.", "Tema: harapan dan tobat."],
    ["Al Qur'an Surat Fussilat ayat 34", "Keburukan ditolak dengan cara yang lebih baik agar permusuhan dapat berubah menjadi kedekatan.", "Tema: pemulihan hubungan."],
    ["Al Qur'an Surat Asy-Syura ayat 38", "Musyawarah menjadi ciri kehidupan orang beriman dalam mengelola urusan bersama.", "Tema: partisipasi dan pengambilan keputusan."],
    ["Al Qur'an Surat Al-Hasyr ayat 18", "Setiap orang diperintah memperhatikan apa yang dipersiapkan untuk hari esok.", "Tema: muhasabah dan perencanaan."],
    ["Al Qur'an Surat Al-'Asr ayat 1–3", "Manusia merugi kecuali yang beriman, beramal saleh, saling menasihati dalam kebenaran, dan kesabaran.", "Tema: waktu dan empat fondasi keselamatan."],
  ];
  dailyInsights.push(...quranInsightBank.map(([source, text, detail]) => ({
    type: "Al Qur'an",
    text,
    source,
    detail,
  })));

  dailyInsights.push(
    {
      type: "Hadits",
      text: "Setiap orang adalah pemimpin dan akan dimintai pertanggungjawaban atas pihak yang berada dalam tanggungannya.",
      source: "Hadits Riwayat Al-Bukhari no. 893",
      detail: "Tema: amanah kepemimpinan dalam keluarga dan kehidupan bersama.",
      url: "https://sunnah.com/bukhari:893",
    },
    {
      type: "Kitab",
      text: "Kelalaian orang tua dalam mengajarkan hal yang bermanfaat, kewajiban agama, dan sunnah dapat menjadi sebab besar kerusakan pendidikan anak.",
      source: "Ibnul Qayyim, Tuhfatul Maudud bi Ahkamil Maulud, bagian pendidikan anak",
      detail: "Intisari terjemahan dari teks Arab yang terverifikasi. Nomor halaman berbeda menurut edisi; rujukan digital menampilkan bagian tersebut pada halaman 80.",
      url: "https://ftp.shamela.ws/book/17582/2375",
    },
    {
      type: "Intisari Kitab",
      text: "Sholat berjamaah menampakkan syiar Islam; pembahasannya perlu diletakkan bersama hukum, syarat, dan keadaan orang yang melaksanakannya.",
      source: "Wahbah Az-Zuhaili, Al-Fiqhul Islami wa Adillatuhu, bab Hukum Sholat Berjamaah",
      detail: "Intisari editorial—bukan kutipan langsung. Halaman mengikuti edisi digital yang digunakan.",
      url: "https://shamela.ws/book/384/1125",
    },
  );

  window.PAIBP_ISLAMIC = { dua, fastingRules, historicDates, dailyInsights };
})();
