(() => {
  "use strict";
  const escapeXml = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]));
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const downloadBlob = (blob, filename) => { const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=filename; document.body.append(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),1500); };
  const slug = (value) => String(value || "dokumen").toLocaleLowerCase("id").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
  function exportXls({filename="data.xls",sheetName="Data",title="Data",rows=[]}={}) {
    const body = rows.map((row,rowIndex)=>`<Row>${row.map((cell)=>`<Cell${rowIndex===0?' ss:StyleID="Header"':''}><Data ss:Type="String">${escapeXml(cell)}</Data></Cell>`).join('')}</Row>`).join('');
    const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Top" ss:WrapText="1"/><Font ss:FontName="Cambria" ss:Size="11"/></Style><Style ss:ID="Header"><Font ss:FontName="Cambria" ss:Size="11" ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#087F68" ss:Pattern="Solid"/><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/></Style></Styles><Worksheet ss:Name="${escapeXml(sheetName).slice(0,31)}"><Table>${body}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>1</SplitHorizontal><TopRowBottomPane>1</TopRowBottomPane></WorksheetOptions></Worksheet></Workbook>`;
    downloadBlob(new Blob(["\ufeff",xml],{type:"application/vnd.ms-excel;charset=utf-8"}),filename);
  }
  async function assetToDataUrl(path) { const r=await fetch(path); if(!r.ok) return ""; const b=await r.blob(); return await new Promise((resolve)=>{const f=new FileReader();f.onload=()=>resolve(f.result);f.onerror=()=>resolve("");f.readAsDataURL(b);}); }
  async function logoData(config){ return config?.logoData || await assetToDataUrl('./logo-spensus.png'); }
  async function exportAssessmentPpt(exam,config,{withKey=false}={}) {
    if(typeof PptxGenJS==='undefined') throw new Error('Pustaka PowerPoint belum dimuat.');
    const pptx=new PptxGenJS(); pptx.layout='LAYOUT_WIDE'; pptx.author='PAIBP SMART SMP'; pptx.subject=exam.spec.title; pptx.title=`${exam.spec.title} Kelas ${exam.spec.grade}`; pptx.company=config.school; pptx.lang='id-ID';
    pptx.defineSlideMaster({title:'PAIBP',background:{color:'F7FBF9'},objects:[{rect:{x:0,y:0,w:13.333,h:.34,fill:{color:'087F68'},line:{color:'087F68'}}},{text:{text:'PAIBP SMART SMP',options:{x:.45,y:7.14,w:5,h:.2,fontFace:'Cambria',fontSize:9,color:'5B706A'}}},{text:{text:config.school,options:{x:7.2,y:7.14,w:5.65,h:.2,fontFace:'Cambria',fontSize:9,color:'5B706A',align:'right'}}}],slideNumber:{x:12.85,y:7.12,color:'5B706A',fontSize:9}});
    const logo=await logoData(config);
    let s=pptx.addSlide('PAIBP');
    if(logo) s.addImage({data:logo,x:.6,y:.65,w:1.15,h:1.15,transparency:0});
    s.addText(config.school,{x:2,y:.68,w:10.3,h:.55,fontFace:'Cambria',fontSize:25,bold:true,color:'063F5C',align:'center'});
    s.addText(exam.spec.title,{x:1,y:1.75,w:11.3,h:.75,fontFace:'Cambria',fontSize:30,bold:true,color:'087F68',align:'center',breakLine:false});
    s.addText(`Kelas ${exam.spec.grade} • ${exam.spec.semester} • Tahun Ajaran ${config.year}`,{x:1.2,y:2.6,w:10.9,h:.4,fontFace:'Cambria',fontSize:16,color:'39564F',align:'center'});
    s.addText(`Cakupan: ${exam.spec.kind==='UKLN'?'Kelas VII 20% • VIII 20% • IX 60%':(exam.spec.chapters||[]).map(id=>'Bab '+id.split('-')[1]).join(', ')}`,{x:1.1,y:3.22,w:11.1,h:.55,fontFace:'Cambria',fontSize:16,color:'39564F',align:'center'});
    s.addText(`${exam.questions.length} pilihan ganda • ${exam.essays.length} uraian`,{x:3.1,y:4.25,w:7.1,h:.7,fontFace:'Cambria',fontSize:22,bold:true,color:'FFFFFF',align:'center',valign:'mid',fill:{color:'087F68'},margin:.12,rounding:true});
    const chunks=[]; for(let i=0;i<exam.questions.length;i+=4) chunks.push(exam.questions.slice(i,i+4));
    chunks.forEach((chunk,chunkIndex)=>{ const slide=pptx.addSlide('PAIBP'); slide.addText(`Pilihan Ganda ${chunkIndex*4+1}–${chunkIndex*4+chunk.length}`,{x:.55,y:.45,w:12.2,h:.42,fontFace:'Cambria',fontSize:21,bold:true,color:'063F5C'}); let y=1.05; chunk.forEach(q=>{ const options=q.options.map((o,i)=>`${String.fromCharCode(65+i)}. ${o}${withKey&&i===q.answer?'  ✓':''}`).join('\n'); slide.addText(`${q.number}. ${q.stem}`,{x:.65,y,w:12,h:.54,fontFace:'Cambria',fontSize:13.5,bold:true,color:'153A33',breakLine:false,margin:.04,fit:'shrink'}); slide.addText(options,{x:.9,y:y+.52,w:11.65,h:.88,fontFace:'Cambria',fontSize:12.5,color:'304F48',breakLine:false,margin:.03,fit:'shrink'}); y+=1.42; }); });
    for(let i=0;i<exam.essays.length;i+=3){ const slide=pptx.addSlide('PAIBP'); slide.addText(`Uraian ${i+1}–${Math.min(i+3,exam.essays.length)}`,{x:.55,y:.45,w:12.2,h:.42,fontFace:'Cambria',fontSize:21,bold:true,color:'063F5C'}); let y=1.25; exam.essays.slice(i,i+3).forEach(q=>{slide.addText(`${q.number}. ${q.prompt}`,{x:.75,y,w:11.85,h:1.45,fontFace:'Cambria',fontSize:17,color:'153A33',breakLine:false,margin:.12,fit:'shrink',fill:{color:'FFFFFF'},line:{color:'CFE3DC'},radius:.12});y+=1.72;}); }
    if(withKey){ s=pptx.addSlide('PAIBP'); s.addText('Kunci Pilihan Ganda',{x:.6,y:.6,w:12,h:.5,fontFace:'Cambria',fontSize:25,bold:true,color:'063F5C'}); s.addText(exam.questions.map(q=>`${q.number}.${String.fromCharCode(65+q.answer)}`).join(' • '),{x:.8,y:1.45,w:11.7,h:4.9,fontFace:'Cambria',fontSize:18,color:'153A33',breakLine:false,margin:.12,fit:'shrink'}); }
    await pptx.writeFile({fileName:`${slug(exam.spec.id)}-${withKey?'soal-kunci':'soal'}.pptx`});
  }
  async function exportArabicPpt(items) {
    if(typeof PptxGenJS==='undefined') throw new Error('Pustaka PowerPoint belum dimuat.');
    const pptx=new PptxGenJS(); pptx.layout='LAYOUT_WIDE'; pptx.author='PAIBP SMART SMP'; pptx.title='Ringkasan Bahasa Arab Praktis'; pptx.lang='id-ID';
    const stages=['Pemula','Menengah','Mahir'];
    let slide=pptx.addSlide(); slide.background={color:'063F5C'}; slide.addText('Ringkasan Bahasa Arab Praktis',{x:.7,y:1.25,w:12,h:.75,fontFace:'Cambria',fontSize:34,bold:true,color:'FFFFFF',align:'center'}); slide.addText(`${items.length} materi • pemula sampai mahir • contoh, kosakata, latihan, dan strategi`,{x:1.2,y:2.25,w:11,h:.5,fontFace:'Cambria',fontSize:18,color:'DCF5EC',align:'center'});
    stages.forEach(stage=>{ const group=items.filter(x=>x.stage===stage); for(let i=0;i<group.length;i+=2){ slide=pptx.addSlide(); slide.background={color:'F7FBF9'}; slide.addText(`${stage} • Materi ${i+1}–${Math.min(i+2,group.length)}`,{x:.55,y:.35,w:12.2,h:.4,fontFace:'Cambria',fontSize:20,bold:true,color:'063F5C'}); group.slice(i,i+2).forEach((item,j)=>{const x=.55+j*6.25; slide.addShape(pptx.ShapeType.roundRect,{x,y:1,w:5.9,h:5.65,rectRadius:.08,fill:{color:'FFFFFF'},line:{color:'CFE3DC'}}); slide.addText(item.title,{x:x+.25,y:1.2,w:5.4,h:.45,fontFace:'Cambria',fontSize:19,bold:true,color:'087F68',fit:'shrink'}); slide.addText(item.goal,{x:x+.25,y:1.72,w:5.4,h:.68,fontFace:'Cambria',fontSize:12.5,color:'304F48',fit:'shrink'}); slide.addText(item.arabic,{x:x+.25,y:2.52,w:5.4,h:.62,fontFace:'Arial',fontSize:20,bold:true,color:'063F5C',align:'right',rtlMode:true,fit:'shrink'}); slide.addText(item.meaning,{x:x+.25,y:3.18,w:5.4,h:.5,fontFace:'Cambria',fontSize:12.5,italic:true,color:'50665F',fit:'shrink'}); slide.addText(`Pola: ${item.formula}`,{x:x+.25,y:3.78,w:5.4,h:.8,fontFace:'Cambria',fontSize:12,color:'153A33',fill:{color:'FFF7DF'},margin:.08,fit:'shrink'}); slide.addText(`Kosakata:\n${(item.vocab||[]).join(' • ')}`,{x:x+.25,y:4.72,w:5.4,h:.75,fontFace:'Cambria',fontSize:11.5,color:'304F48',fit:'shrink'}); slide.addText(`Latihan: ${item.practice}`,{x:x+.25,y:5.6,w:5.4,h:.65,fontFace:'Cambria',fontSize:11.5,bold:true,color:'087F68',fit:'shrink'});}); }});
    await pptx.writeFile({fileName:'ringkasan-bahasa-arab-praktis.pptx'});
  }
  window.PAIBP_OFFICE={exportXls,exportAssessmentPpt,exportArabicPpt};
})();
