(() => {
  "use strict";
  const VERSION="55", CONFIG=window.PAIBP_CONFIG||{};
  const ENDPOINT=String(CONFIG.syncEndpoint||CONFIG.realtimeEndpoint||"").trim();
  const READY=CONFIG.realtimeEnabled!==false&&/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec(?:\?.*)?$/i.test(ENDPOINT);
  const SESSION="paibp-smart-realtime-session-v55", QUEUE="paibp-smart-realtime-queue-v55";
  const $=(s,r=document)=>r?.querySelector?.(s)||null,$$=(s,r=document)=>[...(r?.querySelectorAll?.(s)||[])];
  const parse=(v,f)=>{try{return JSON.parse(v)}catch{return f}},clean=v=>String(v||"").replace(/\s+/g," ").trim();
  let snapshotTimer=0,lastSnapshot=null,sending=false;
  function sessionId(){let id=sessionStorage.getItem(SESSION);if(!id){id=`s55-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;sessionStorage.setItem(SESSION,id);}return id;}
  function device(){const ua=navigator.userAgent||"";if(/android/i.test(ua))return"Android";if(/iphone|ipad|ipod/i.test(ua))return"iPhone/iPad";if(/windows/i.test(ua))return"Windows";if(/mac/i.test(ua))return"macOS";return"Perangkat lain";}
  function role(){return window.PAIBP_V55?.role?.()||document.body?.dataset.portalRole||"umum";}
  function identity(){const key=role()==="student"?"paibp-smart-student-identity-v1":"paibp-smart-teacher-identity-v1";return parse(localStorage.getItem(key),{})||{};}
  function context(){const panel=$(".workspace-panel:not([hidden])"),chapter=$("[data-chapter].active,[data-chapter-id].active,[data-material-id].active");return{space:panel?.dataset.panel||panel?.id||location.pathname.split('/').pop()||'beranda',chapter:chapter?.dataset.chapter||chapter?.dataset.chapterId||chapter?.dataset.materialId||""};}
  function recordData(action,extra={}){const i=identity(),c=context();return{id:`a55-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`,sessionId:sessionId(),role:role(),userName:i.name||i.teacherName||i.studentName||"",school:i.workUnit||i.school||i.teacherSchool||i.studentSchool||"",studentClass:i.className||i.class||i.grade||"",studentNumber:i.number||i.absen||"",action,space:extra.space||c.space,chapter:extra.chapter||c.chapter,section:extra.section||"",durationSeconds:Number(extra.durationSeconds||0),device:device(),userAgent:navigator.userAgent||"",online:navigator.onLine,referrer:document.referrer||"",pageUrl:location.href,origin:location.origin,appVersion:VERSION};}
  function queueRead(){const q=parse(localStorage.getItem(QUEUE),[]);return Array.isArray(q)?q:[];}function queueWrite(q){try{localStorage.setItem(QUEUE,JSON.stringify(q.slice(-100)));}catch{}}
  function payload(action,data){return JSON.stringify({app:"paibp-smart",version:VERSION,action,data,origin:location.origin});}
  async function send(action,data){if(!READY)throw new Error("Endpoint belum lengkap");const body=payload(action,data);if(navigator.sendBeacon){const ok=navigator.sendBeacon(ENDPOINT,new Blob([body],{type:"text/plain;charset=UTF-8"}));if(ok)return true;}await fetch(ENDPOINT,{method:"POST",mode:"no-cors",cache:"no-store",keepalive:body.length<60000,headers:{"Content-Type":"text/plain;charset=UTF-8"},body});return true;}
  function record(action,extra={}){const data=recordData(action,extra);if(READY&&navigator.onLine){send("activity",data).catch(()=>{const q=queueRead();q.push({action:"activity",data});queueWrite(q);});}else{const q=queueRead();q.push({action:"activity",data});queueWrite(q);}return data;}
  async function flush(){if(sending||!READY||!navigator.onLine)return;sending=true;try{const q=queueRead();while(q.length){try{await send(q[0].action,q[0].data);q.shift();queueWrite(q);}catch{break;}}}finally{sending=false;}}
  function jsonp(action,timeout=12000){return new Promise((resolve,reject)=>{if(!READY){reject(new Error("Endpoint belum lengkap"));return;}const cb=`paibpV55_${Date.now()}_${Math.random().toString(36).slice(2)}`,node=document.createElement("script"),url=new URL(ENDPOINT);let done=false;const finish=(e,v)=>{if(done)return;done=true;clearTimeout(t);try{delete window[cb]}catch{}node.remove();e?reject(e):resolve(v)};window[cb]=v=>finish(null,v);url.searchParams.set("action",action);url.searchParams.set("callback",cb);url.searchParams.set("_v",Date.now());node.src=url.href;node.async=true;node.onerror=()=>finish(new Error("Server tidak dapat dijangkau"));const t=setTimeout(()=>finish(new Error("Server melewati batas waktu")),timeout);document.head.append(node);});}
  function ensureStats(){const hero=$(".hero-main-v25");if(!hero)return null;let b=$("#v55-live-stats",hero);if(!b){b=document.createElement("div");b.id="v55-live-stats";b.innerHTML='<article><strong data-total>—</strong><span>Total kunjungan</span></article><article><strong data-today>—</strong><span>Kunjungan hari ini</span></article><article><strong data-online>—</strong><span>Aktif sekarang</span></article><article><strong data-work>—</strong><span>Tugas terkirim</span></article>';$(".hero-actions-v25",hero)?.insertAdjacentElement("afterend",b)||hero.append(b);}return b;}
  function ensureStatus(){const hero=$(".hero-main-v25");if(!hero)return null;let b=$("#v55-live-status",hero);if(!b){b=document.createElement("div");b.id="v55-live-status";b.textContent="Menghubungkan rekap lintas perangkat…";$(".eyebrow-v25",hero)?.insertAdjacentElement("afterend",b)||hero.prepend(b);}return b;}
  function warnings(state,message){const pattern=/mode lokal|belum real-time lintas perangkat|statistik perangkat ini ditampilkan|statistik hanya berasal dari perangkat ini|aktifkan sinkronisasi untuk angka lintas perangkat/i;$$('section,article,aside,div').forEach(n=>{if(n.children.length>20||!pattern.test(clean(n.textContent)))return;const h=$("h1,h2,h3,h4,strong",n),p=$("p",n);if(h)h.textContent=state==="online"?"Sinkronisasi real-time lintas perangkat aktif":"Sinkronisasi sedang menyambung kembali";if(p)p.textContent=message;});}
  function latestSection(visitors){let section=$("#v55-latest-visitors");if(!section){section=document.createElement("section");section.id="v55-latest-visitors";section.className="container";const hero=$(".hero-v25");hero?.insertAdjacentElement("afterend",section);}if(!section)return;section.innerHTML=`<header><div><span>AKSES OTOMATIS</span><h2>Kunjungan terbaru</h2></div><p>Setiap perangkat tercatat otomatis; nama hanya tampil saat identitas tersedia.</p></header><div class="v55-visitor-strip">${(visitors||[]).slice(0,8).map(v=>`<article><strong>${escape(v.label||v.name||"Pengunjung")}</strong><small>${escape([v.role,v.school,v.device,v.relativeTime].filter(Boolean).join(" • "))}</small></article>`).join("")||'<article><strong>Menunggu akses baru</strong><small>Pengunjung berikutnya akan tampil otomatis.</small></article>'}</div>`;}
  function escape(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);}
  function render(s){lastSnapshot=s;const stats=s?.stats||{},b=ensureStats();if(b){$("[data-total]",b).textContent=Number(stats.totalSessions||0).toLocaleString("id-ID");$("[data-today]",b).textContent=Number(stats.todaySessions||0).toLocaleString("id-ID");$("[data-online]",b).textContent=Number(stats.onlineNow||0).toLocaleString("id-ID");$("[data-work]",b).textContent=Number(stats.totalSubmissions||stats.submissions||0).toLocaleString("id-ID");}const st=ensureStatus();if(st){st.dataset.state="online";st.textContent="Sinkronisasi real-time lintas perangkat aktif";}warnings("online","Kunjungan, aktivitas, dan pekerjaan diperbarui dari server pada seluruh perangkat.");latestSection(s?.latestVisitors||[]);document.documentElement.dataset.realtimeV55="online";document.dispatchEvent(new CustomEvent("paibp-realtime-v55",{detail:s}));}
  function fail(e){const st=ensureStatus();if(st){st.dataset.state="error";st.textContent="Sinkronisasi sedang menyambung kembali";}warnings("error",`Data disimpan sementara dan dikirim otomatis saat server tersambung kembali.`);document.documentElement.dataset.realtimeV55="error";}
  async function refresh(){clearTimeout(snapshotTimer);try{const s=await jsonp("publicSnapshot",14000);if(!s||s.ok===false)throw new Error(s?.error||"Respons server tidak valid");render(s);}catch(e){fail(e);}finally{snapshotTimer=setTimeout(refresh,60000);}}
  function init(){ensureStatus();ensureStats();record("session-start");flush();refresh();document.addEventListener("click",e=>{const t=e.target.closest("[data-open-panel],[data-chapter],[data-chapter-id],[data-material-id],[data-teacher-doc],[data-islamic-view]");if(!t)return;if(t.matches("[data-open-panel]"))record(`buka-${t.dataset.openPanel||"ruang"}`);else if(t.matches("[data-chapter],[data-chapter-id],[data-material-id]"))record("buka-bab");else record("buka-bagian");},{passive:true,capture:true});window.addEventListener("online",()=>{flush();refresh();});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"){record("kembali-aktif");refresh();}});setInterval(()=>{if(document.visibilityState==="visible")record("heartbeat");},120000);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
  window.PAIBP_REALTIME_V55=Object.freeze({version:VERSION,configured:READY,record,refresh,flush,get lastSnapshot(){return lastSnapshot;}});
})();
